= UMC Product API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]

== Admin dashboard

=== 대시보드_action-queue_api_문서화
operation::admin-dashboard-controller-test/대시보드_action-queue_api_문서화[snippets='http-request,http-response']

=== 대시보드_context_api_응답
operation::admin-dashboard-controller-test/대시보드_context_api_응답[snippets='http-request,http-response']

=== 대시보드_operations_api_응답
operation::admin-dashboard-controller-test/대시보드_operations_api_응답[snippets='http-request,http-response']

=== 대시보드_risk-challengers_api_응답
operation::admin-dashboard-controller-test/대시보드_risk-challengers_api_응답[snippets='http-request,http-response']

=== 대시보드_summary_api_문서화
operation::admin-dashboard-controller-test/대시보드_summary_api_문서화[snippets='http-request,http-response']

== Admin school analytics

=== 학교별_summary_api_문서화
operation::admin-school-analytics-controller-test/학교별_summary_api_문서화[snippets='http-request,http-response']

== Admin school query

=== 학교_상세정보를_조회합니다
operation::admin-school-query-controller-test/학교_상세정보를_조회합니다[snippets='http-request,http-response,path-parameters,response-fields']

=== 학교_전체_목록을_조회합니다
operation::admin-school-query-controller-test/학교_전체_목록을_조회합니다[snippets='http-request,http-response,response-fields']

== Chapter command

=== 신규_지부를_생성한다
operation::chapter-command-controller-test/신규_지부를_생성한다[snippets='http-request,http-response,request-fields']

== Chapter query

=== 지부_목록을_조회합니다
operation::chapter-query-controller-test/지부_목록을_조회합니다[snippets='http-request,http-response,response-fields']

== Gisu command

=== 기수를_삭제한다
operation::gisu-command-controller-test/기수를_삭제한다[snippets='http-request,http-response,path-parameters']

=== 신규_기수를_추가한다
operation::gisu-command-controller-test/신규_기수를_추가한다[snippets='http-request,http-response,request-fields']

=== 현재_기수를_설정한다
operation::gisu-command-controller-test/현재_기수를_설정한다[snippets='http-request,http-response,path-parameters']

== Gisu query

=== 기수_목록을_페이징_조회한다
operation::gisu-query-controller-test/기수_목록을_페이징_조회한다[snippets='http-request,http-response,query-parameters,response-fields']

=== 기수_전체_목록을_조회한다
operation::gisu-query-controller-test/기수_전체_목록을_조회한다[snippets='http-request,http-response,response-fields']

=== 활성화된_기수를_조회한다
operation::gisu-query-controller-test/활성화된_기수를_조회한다[snippets='http-request,http-response,response-fields']

== School command

=== 총괄_신규학교를_추가한다
operation::school-command-controller-test/총괄_신규학교를_추가한다[snippets='http-request,http-response,request-fields']

=== 총괄_학교를_일괄_삭제한다
operation::school-command-controller-test/총괄_학교를_일괄_삭제한다[snippets='http-request,http-response,request-fields']

=== 총괄_학교정보를_수정한다
operation::school-command-controller-test/총괄_학교정보를_수정한다[snippets='http-request,http-response,path-parameters,request-fields']

== School link query

=== 학교_링크를_조회합니다
operation::school-link-query-controller-test/학교_링크를_조회합니다[snippets='http-request,http-response,path-parameters,response-fields']

