package com.umc.product.recruitment.domain.exception;

import com.umc.product.global.response.code.BaseCode;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum RecruitmentErrorCode implements BaseCode {

    RECRUITMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "RECRUITMENT-0001", "모집을 찾을 수 없습니다."),
    RECRUITMENT_NOT_DRAFT(HttpStatus.CONFLICT, "RECRUITMENT-0002", "임시저장 상태의 모집만 편집할 수 있습니다."),
    RECRUITMENT_INACTIVE(HttpStatus.CONFLICT, "RECRUITMENT-0003", "활성 중인 모집은 편집할 수 없습니다."),
    RECRUITMENT_SCHEDULE_NOT_FOUND(HttpStatus.NOT_FOUND, "RECRUITMENT-004", "해당 타입에 해당하는 모집 일정을 찾을 수 없습니다."),
    RECRUITMENT_ALREADY_PUBLISHED(HttpStatus.BAD_REQUEST, "RECRUITMENT-005", "이미 발행된 모집입니다."),
    RECRUITMENT_PUBLISH_CONFLICT(HttpStatus.BAD_REQUEST, "RECRUITMENT-006", "현재 이미 발행되어 있는 모집이 있습니다."),
    RECRUITMENT_PUBLISH_VALIDATION_FAILED(HttpStatus.BAD_REQUEST, "RECRUITMENT-007", "발행하기에 검증되지 않은 필드가 있습니다."),
    RECRUITMENT_NOT_PUBLISHED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0008", "발행 상태의 모집만 수정할 수 있습니다."),
    RECRUITMENT_DELETE_FORBIDDEN_HAS_APPLICANTS(HttpStatus.BAD_REQUEST, "RECRUITMENT-0009", "지원자가 있는 모집은 삭제할 수 없습니다."),
    RECRUITMENT_FORM_MISMATCH(HttpStatus.BAD_REQUEST, "RECRUITMENT-00010", "지원하려는 폼이 해당 모집의 폼과 일치하지 않습니다."),
    RECRUITMENT_ALREADY_APPLIED(HttpStatus.CONFLICT, "RECRUITMENT-00011", "이미 지원한 모집입니다."),
    RECRUITMENT_APPLICATION_INCONSISTENT(HttpStatus.INTERNAL_SERVER_ERROR, "RECRUITMENT-00012",
        "지원서 제출 처리 중 내부 데이터 오류가 발생했습니다."),
    PREFERRED_PART_EXCEEDS_MAX_COUNT(HttpStatus.BAD_REQUEST, "RECRUITMENT-00013",
        "선호 파트의 개수가 최대 허용 개수를 초과했습니다."),
    INTERVIEW_TIMETABLE_NOT_SET(HttpStatus.BAD_REQUEST, "RECRUITMENT-00014",
        "면접 일정표가 설정되지 않은 모집입니다."),
    INTERVIEW_PREFERENCE_EMPTY(HttpStatus.BAD_REQUEST, "RECRUITMENT-00015",
        "면접 선호 일시 목록이 비어있습니다."),
    INTERVIEW_PREFERENCE_OUT_OF_RANGE(HttpStatus.BAD_REQUEST, "RECRUITMENT-00016",
        "면접 선호 일시가 모집의 면접 일정표에 포함되지 않습니다."),
    INTERVIEW_PREFERENCE_INVALID_SLOT(HttpStatus.BAD_REQUEST, "RECRUITMENT-00017",
        "면접 선호 일시가 올바르지 않은 형식입니다."),
    INTERVIEW_PREFERENCE_INVALID_FORMAT(HttpStatus.BAD_REQUEST, "RECRUITMENT-00018",
        "면접 선호 일시의 형식이 올바르지 않습니다."),
    RECRUITMENT_APPLY_WINDOW_NOT_SET(HttpStatus.BAD_REQUEST, "RECRUITMENT-00019",
        "지원 기간이 설정되지 않은 모집입니다."),
    RECRUITMENT_APPLY_WINDOW_INVALID(HttpStatus.BAD_REQUEST, "RECRUITMENT-00020",
        "지원 기간이 올바르지 않습니다."),
    RECRUITMENT_APPLY_NOT_STARTED(HttpStatus.BAD_REQUEST, "RECRUITMENT-00021",
        "아직 지원 기간이 시작되지 않은 모집입니다."),
    RECRUITMENT_APPLY_CLOSED(HttpStatus.BAD_REQUEST, "RECRUITMENT-00022",
        "이미 지원 기간이 종료된 모집입니다."),
    ACTIVE_RECRUITMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "RECRUITMENT-0023",
        "활성화된 모집을 찾을 수 없습니다."),
    DRAFT_FORM_RESPONSE_ALREADY_EXISTS(HttpStatus.CONFLICT, "RECRUITMENT-0024",
        "해당 모집에 대한 임시저장된 지원서가 이미 존재합니다."),
    INTERVIEW_TIMETABLE_INVALID(HttpStatus.BAD_REQUEST, "RECRUITMENT-0025",
        "면접 일정표가 올바르지 않습니다."),
    PREFERRED_PART_INVALID_MAX_COUNT(HttpStatus.BAD_REQUEST, "RECRUITMENT-0026",
        "선호 파트의 최대 개수가 올바르지 않습니다."),
    PREFERRED_PART_INVALID(HttpStatus.BAD_REQUEST, "RECRUITMENT-0027",
        "선호 파트가 올바르지 않습니다."),
    MULTIPLE_ACTIVE_RECRUITMENTS(HttpStatus.INTERNAL_SERVER_ERROR, "RECRUITMENT-0028",
        "하나의 학교와 기수에 대해 여러 개의 발행된 모집이 존재합니다."),
    RECRUITMENT_SCHEDULE_INVALID(HttpStatus.BAD_REQUEST, "RECRUITMENT-0029",
        "모집 일정이 올바르지 않습니다."),
    RECRUITMENT_SCHEDULE_APPLY_START_FROZEN(HttpStatus.BAD_REQUEST, "RECRUITMENT-0030",
        "지원 시작 일정은 발행 이후 변경할 수 없습니다."),
    RECRUITMENT_SCHEDULE_APPLY_END_SHORTEN_FORBIDDEN(HttpStatus.BAD_REQUEST, "RECRUITMENT-0031",
        "지원 종료 일정을 앞당길 수 없습니다."),
    RECRUITMENT_SCHEDULE_INTERVIEW_ADVANCE_FORBIDDEN(HttpStatus.BAD_REQUEST, "RECRUITMENT-0032",
        "면접 일정을 앞당길 수 없습니다."),
    RECRUITMENT_SCHEDULE_INTERVIEW_SHORTEN_FORBIDDEN(HttpStatus.BAD_REQUEST, "RECRUITMENT-0033",
        "면접 일정을 단축할 수 없습니다."),
    RECRUITMENT_SCHEDULE_INVALID_ORDER(HttpStatus.BAD_REQUEST, "RECRUITMENT-0034",
        "모집 일정의 순서가 올바르지 않습니다."),
    RECRUITMENT_PUBLISH_TITLE_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0035",
        "모집 제목은 필수 항목입니다."),
    RECRUITMENT_PUBLISH_PART_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0036",
        "모집 파트는 최소 하나 이상 선택해야 합니다."),
    RECRUITMENT_PUBLISH_SCHEDULE_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0037",
        "모집 일정은 필수 항목입니다."),
    RECRUITMENT_PUBLISH_APPLY_START_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0038",
        "지원 시작 일정은 필수 항목입니다."),
    RECRUITMENT_PUBLISH_APPLY_END_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0039",
        "지원 종료 일정은 필수 항목입니다."),
    RECRUITMENT_PUBLISH_DOC_RESULT_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0040",
        "서류 결과 발표 일정은 필수 항목입니다."),
    RECRUITMENT_PUBLISH_INTERVIEW_START_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0041",
        "면접 시작 일정은 필수 항목입니다."),
    RECRUITMENT_PUBLISH_INTERVIEW_END_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0042",
        "면접 종료 일정은 필수 항목입니다."),
    RECRUITMENT_PUBLISH_FINAL_RESULT_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0043",
        "최종 결과 발표 일정은 필수 항목입니다."),
    RECRUITMENT_PUBLISH_SCHEDULE_ORDER_INVALID(HttpStatus.BAD_REQUEST, "RECRUITMENT-0044",
        "모집 일정의 순서가 올바르지 않습니다."),
    RECRUITMENT_PUBLISH_QUESTION_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0045",
        "모집 질문은 최소 하나 이상 필요합니다."),
    RECRUITMENT_PUBLISH_MAX_PREFERRED_PART_INVALID(HttpStatus.BAD_REQUEST, "RECRUITMENT-0046",
        "선호 파트의 최대 개수가 올바르지 않습니다."),
    RECRUITMENT_FORBIDDEN(HttpStatus.FORBIDDEN, "RECRUITMENT-0047",
        "해당 모집에 접근할 수 있는 권한이 없습니다."),
    RECRUITMENT_PUBLISH_PREFERRED_PART_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0048",
        "선호 파트 질문이 필요합니다."),
    PREFERRED_PART_REQUIRED_COUNT_MISMATCH(HttpStatus.BAD_REQUEST, "RECRUITMENT-0049",
        "선호 파트 질문의 필수 개수와 현재 선택 개수가 일치하지 않습니다."),
    RECRUITMENT_SCHEDULE_NOT_COVER_TIMETABLE(HttpStatus.BAD_REQUEST, "RECRUITMENT-0050",
        "면접 일정표가 면접 일정에 포함되지 않습니다."),
    APPLICATION_NOT_BELONGS_TO_RECRUITMENT(HttpStatus.BAD_REQUEST, "RECRUITMENT-0051",
        "해당 지원서는 이 모집에 속하지 않습니다."),
    APPLICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "RECRUITMENT-0052", "지원서를 찾을 수 없습니다."),
    APPLICATION_RECRUITMENT_MISMATCH(HttpStatus.INTERNAL_SERVER_ERROR, "RECRUITMENT-0053",
        "지원서와 모집의 데이터가 일치하지 않습니다."),
    INTERVIEW_SHEET_PART_NOT_OPEN(HttpStatus.BAD_REQUEST, "RECRUITMENT-0054", "해당 파트는 모집 중이 아닙니다."),
    INTERVIEW_SHEET_QUESTION_DUPLICATE(HttpStatus.BAD_REQUEST, "RECRUITMENT-0055", "질문 ID 목록에 중복이 있습니다."),
    INTERVIEW_SHEET_QUESTION_MISMATCH(HttpStatus.BAD_REQUEST, "RECRUITMENT-0056", "질문 ID 목록이 해당 파트의 질문과 일치하지 않습니다."),
    INTERVIEW_SHEET_QUESTION_NOT_FOUND(HttpStatus.NOT_FOUND, "RECRUITMENT-0057", "해당 질문을 찾을 수 없습니다."),
    INTERVIEW_SHEET_QUESTION_NOT_BELONGS_TO_RECRUITMENT(HttpStatus.BAD_REQUEST, "RECRUITMENT-0058",
        "해당 질문은 이 모집에 속하지 않습니다."),
    INTERVIEW_ASSIGNMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "RECRUITMENT-0059", "면접 배정을 찾을 수 없습니다."),
    INTERVIEW_ASSIGNMENT_NOT_BELONGS_TO_RECRUITMENT(HttpStatus.BAD_REQUEST, "RECRUITMENT-0060",
        "해당 면접 배정은 이 모집에 속하지 않습니다."),
    INTERVIEW_LIVE_QUESTION_NOT_FOUND(HttpStatus.NOT_FOUND, "RECRUITMENT-0061", "해당하는 즉석 질문을 찾을 수 없습니다."),
    INTERVIEW_LIVE_QUESTION_NOT_BELONGS_TO_ASSIGNMENT(HttpStatus.BAD_REQUEST, "RECRUITMENT-0062",
        "해당 질문은 이 면접 배정에 속하지 않습니다."),
    INTERVIEW_LIVE_QUESTION_NOT_EDITABLE(HttpStatus.FORBIDDEN, "RECRUITMENT-0063", "본인이 작성한 질문만 수정하거나 삭제할 수 있습니다."),
    INTERVIEW_WINDOW_NOT_SET(HttpStatus.BAD_REQUEST, "RECRUITMENT-0064",
        "면접 일정이 설정되지 않은 모집입니다."),
    INTERVIEW_SLOT_NOT_FOUND(HttpStatus.NOT_FOUND, "RECRUITMENT-0065", "해당 면접 슬롯이 존재하지 않습니다."),
    INTERVIEW_SLOT_NOT_IN_RECRUITMENT(HttpStatus.BAD_REQUEST, "RECRUITMENT-0066", "해당 면접 슬롯이 해당 모집 소속이 아닙니다."),
    INTERVIEW_ASSIGNMENT_ONLY_DOC_PASSED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0067", "서류에 합격한 지원서만 면접 시간을 할당할 수 있습니다."),
    INTERVIEW_ASSIGNMENT_ALREADY_EXISTS(HttpStatus.BAD_REQUEST, "RECRUITMENT-0068", "이미 면접 시간이 할당된 서류입니다."),
    INTERVIEW_ASSIGNMENT_NOT_IN_RECRUITMENT(HttpStatus.BAD_REQUEST, "RECRUITMENT-0069", "해당 면접 할당이 해당 모집 소속이 아닙니다."),
    FINAL_SELECTED_PART_REQUIRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0070",
        "최종 합격 처리 시 선택 파트(selectedPart)는 필수입니다."),
    FINAL_SELECTED_PART_NOT_PREFERRED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0071",
        "최종 합격 처리 시 선택 파트(selectedPart)는 지원자가 선택한 지원 파트(preferred) 중 하나여야 합니다."),
    INTERVIEW_TIMETABLE_SLOT_MINUTES_UPDATE_FORBIDDEN(HttpStatus.NOT_FOUND, "RECRUITMENT-0072",
        "이미 할당된 면접이 있는 모집은 slotMinutes를 수정할 수 없습니다."),
    SLOT_MINUTES_TOO_SMALL(HttpStatus.BAD_REQUEST, "RECRUITMENT-0072", "면접 시간이 너무 짧습니다."),
    SLOT_STARTS_AT_NOT_SET(HttpStatus.BAD_REQUEST, "RECRUITMENT-0073", "면접 슬롯의 시작 시간이 설정되지 않았습니다."),
    INTERVIEW_EVALUATION_NOT_STARTED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0074", "면접 시작 전에는 평가를 제출할 수 없습니다."),
    INTERVIEW_ALREADY_ASSIGNED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0075", "면접 배정이 존재하는 지원서는 서류 결과를 변경할 수 없습니다."),
    BASE_RECRUITMENT_NOT_PUBLISHED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0076", "배포되지 않은 모집을 기반으로 추가 모집을 만들 수 없습니다."),
    RECRUITMENT_ID_MISSING(HttpStatus.BAD_REQUEST, "RECRUITMENT-0077", "ID가 생성되지 않은 상태에서 Root를 설정할 수 없습니다."),
    MAX_PREFERRED_PART_EXCEEDS_OPEN_PARTS(HttpStatus.BAD_REQUEST, "RECRUITMENT-0078",
        "최대 희망 파트 개수가 현재 오픈된 파트 수보다 많습니다."),
    ROOT_RECRUITMENT_NOT_FOUND(HttpStatus.BAD_REQUEST, "RECRUITMENT-0079", "기준 모집을 찾을 수 없습니다."),
    EXTENSION_SCHEDULE_INCONSISTENT_WITH_ROOT(HttpStatus.BAD_REQUEST, "RECRUITMENT-0080",
        "추가 모집의 면접/최종 일정이 기준 모집과 다릅니다."),
    DOC_RESULT_ALREADY_PUBLISHED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0081", "서류 결과가 이미 공개되어 평가를 수정할 수 없습니다."),
    INTERVIEW_NOT_STARTED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0082", "면접이 아직 시작되지 않은 지원자를 평가할 수 없습니다."),
    FINAL_RESULT_ALREADY_PUBLISHED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0083", "최종 결과 공개 이후에는 수정이 불가능합니다."),
    INTERVIEW_SLOT_ALREADY_ENDED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0084", "이미 끝난 면접 슬롯에 면접자를 할당할 수 없습니다."),
    INTERVIEW_ALREADY_EVALUATED(HttpStatus.BAD_REQUEST, "RECRUITMENT-0085", "이미 평가가 등록된 지원서입니다."),
    ;

    private final HttpStatus httpStatus;
    private final String code;
    private final String message;
}
