-- 서류/최종 판정 이력을 append-only로 보존한다.
-- 판정 축과 등록 축이 recruiting_application의 status_changed_* 슬롯을 공유해 덮어쓰므로,
-- 등록 전이 이후에도 판정 시각·담당자 정보 스냅샷을 감사 목적으로 조회할 수 있도록 분리 저장한다.
CREATE TABLE public.recruiting_decision_history
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_application_id BIGINT                                  NOT NULL,
    decision_status           VARCHAR(255)                            NOT NULL,
    decided_by_member_id      BIGINT                                  NOT NULL,
    decided_at                TIMESTAMP WITH TIME ZONE                NOT NULL,
    decider_role_type         VARCHAR(255),
    decider_chapter_id        BIGINT,
    decider_chapter_name      VARCHAR(255),
    decider_school_id         BIGINT,
    decider_school_name       VARCHAR(255),
    decider_name              VARCHAR(30)                            NOT NULL,
    decider_nickname          VARCHAR(20)                            NOT NULL,
    CONSTRAINT pk_recruiting_decision_history PRIMARY KEY (id),
    CONSTRAINT fk_recruiting_decision_history_application
        FOREIGN KEY (recruiting_application_id) REFERENCES public.recruiting_application (id),
    CONSTRAINT uk_recruiting_decision_history_application UNIQUE (recruiting_application_id),
    CONSTRAINT recruiting_decision_history_status_check CHECK (
        decision_status IN ('DOCUMENT_FAILED', 'FINAL_PASSED', 'FINAL_FAILED')
    )
);

CREATE INDEX ix_recruiting_decision_history_decided_at
    ON public.recruiting_decision_history (decided_at);

CREATE INDEX ix_recruiting_decision_history_decider
    ON public.recruiting_decision_history (decided_by_member_id, decided_at);
