-- 회원 전역 시스템 역할을 저장할 테이블과 허용 가능한 역할 타입을 정의한다.
CREATE TABLE public.member_system_role
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) with time zone             NOT NULL,
    updated_at timestamp(6) with time zone             NOT NULL,
    member_id  bigint                                  NOT NULL,
    role_type  character varying(50)                   NOT NULL,
    CONSTRAINT member_system_role_pkey PRIMARY KEY (id),
    CONSTRAINT uk_member_system_role_member_role UNIQUE (member_id, role_type),
    CONSTRAINT member_system_role_role_type_check CHECK (
        (role_type)::text = ANY (ARRAY[
            ('SUPER_ADMIN'::character varying)::text
        ])
    )
);

-- 회원 삭제 시 시스템 역할도 함께 제거되도록 member FK를 추가한다.
ALTER TABLE ONLY public.member_system_role
    ADD CONSTRAINT fk_member_system_role_member
        FOREIGN KEY (member_id) REFERENCES public.member (id) ON DELETE CASCADE;

-- 기수별 legacy SUPER_ADMIN을 회원 기준으로 중복 제거해 시스템 역할로 이관한다.
INSERT INTO public.member_system_role (created_at, updated_at, member_id, role_type)
SELECT DISTINCT
    now(),
    now(),
    c.member_id,
    'SUPER_ADMIN'
FROM public.challenger_role cr
JOIN public.challenger c ON c.id = cr.challenger_id
JOIN public.member m ON m.id = c.member_id
WHERE cr.role_type = 'SUPER_ADMIN'
ON CONFLICT (member_id, role_type) DO NOTHING;

-- 이관이 끝난 SUPER_ADMIN을 기수별 ChallengerRole 저장소에서 제거한다.
DELETE FROM public.challenger_role
WHERE role_type = 'SUPER_ADMIN';

-- SUPER_ADMIN을 허용하던 기존 challenger_role 역할 타입 제약을 제거한다.
ALTER TABLE public.challenger_role
    DROP CONSTRAINT IF EXISTS challenger_role_role_type_check;

-- challenger_role에는 기수별 운영진 역할만 저장할 수 있도록 제약을 다시 생성한다.
ALTER TABLE public.challenger_role
    ADD CONSTRAINT challenger_role_role_type_check CHECK (
        (role_type)::text = ANY (ARRAY[
            ('CENTRAL_PRESIDENT'::character varying)::text,
            ('CENTRAL_VICE_PRESIDENT'::character varying)::text,
            ('CENTRAL_OPERATING_TEAM_MEMBER'::character varying)::text,
            ('CENTRAL_EDUCATION_TEAM_MEMBER'::character varying)::text,
            ('CHAPTER_PRESIDENT'::character varying)::text,
            ('SCHOOL_PRESIDENT'::character varying)::text,
            ('SCHOOL_VICE_PRESIDENT'::character varying)::text,
            ('SCHOOL_PART_LEADER'::character varying)::text,
            ('SCHOOL_ETC_ADMIN'::character varying)::text
        ])
    );

-- 이력 데이터에서도 회원 전역 시스템 역할과 중복되는 legacy SUPER_ADMIN을 제거한다.
DELETE FROM public.challenger_record
WHERE challenger_role_type = 'SUPER_ADMIN';

-- SUPER_ADMIN을 허용하던 기존 challenger_record 역할 타입 제약을 제거한다.
ALTER TABLE public.challenger_record
    DROP CONSTRAINT IF EXISTS challenger_record_challenger_role_type_check;

-- challenger_record에는 기수별 운영진 역할만 기록할 수 있도록 제약을 다시 생성한다.
ALTER TABLE public.challenger_record
    ADD CONSTRAINT challenger_record_challenger_role_type_check CHECK (
        (challenger_role_type)::text = ANY (ARRAY[
            ('CENTRAL_PRESIDENT'::character varying)::text,
            ('CENTRAL_VICE_PRESIDENT'::character varying)::text,
            ('CENTRAL_OPERATING_TEAM_MEMBER'::character varying)::text,
            ('CENTRAL_EDUCATION_TEAM_MEMBER'::character varying)::text,
            ('CHAPTER_PRESIDENT'::character varying)::text,
            ('SCHOOL_PRESIDENT'::character varying)::text,
            ('SCHOOL_VICE_PRESIDENT'::character varying)::text,
            ('SCHOOL_PART_LEADER'::character varying)::text,
            ('SCHOOL_ETC_ADMIN'::character varying)::text
        ])
    );
