ALTER TABLE chat_message
    ADD COLUMN client_message_id UUID,
    ADD COLUMN client_payload_fingerprint VARCHAR(64),
    ADD COLUMN edited_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE chat_message
    ADD CONSTRAINT uq_chat_message_room_sender_client
        UNIQUE (room_id, sender_member_id, client_message_id);

CREATE TABLE chat_message_mention
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    message_id BIGINT                                  NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_chat_message_mention PRIMARY KEY (id),
    CONSTRAINT uq_chat_message_mention_message_member UNIQUE (message_id, member_id),
    CONSTRAINT fk_chat_message_mention_message
        FOREIGN KEY (message_id) REFERENCES chat_message (id) ON DELETE CASCADE
);

CREATE INDEX idx_chat_message_mention_member_id
    ON chat_message_mention (member_id);

CREATE TABLE chat_message_reaction
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    message_id BIGINT                                  NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    emoji      VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_chat_message_reaction PRIMARY KEY (id),
    CONSTRAINT uq_chat_message_reaction_message_member_emoji UNIQUE (message_id, member_id, emoji),
    CONSTRAINT fk_chat_message_reaction_message
        FOREIGN KEY (message_id) REFERENCES chat_message (id) ON DELETE CASCADE
);

CREATE INDEX idx_chat_message_reaction_message_emoji
    ON chat_message_reaction (message_id, emoji);
