DROP TABLE report;

CREATE TABLE report
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reporter_id  BIGINT                                  NOT NULL,
    target_type  VARCHAR(32)                             NOT NULL,
    target_id    BIGINT                                  NOT NULL,
    status       VARCHAR(20)                             NOT NULL,
    reason       VARCHAR(500),
    thread_id    BIGINT,
    reason_code  VARCHAR(32),
    created_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    CONSTRAINT pk_report PRIMARY KEY (id),
    CONSTRAINT uq_report_reporter_target UNIQUE (reporter_id, target_type, target_id),
    CONSTRAINT fk_report_community_thread
        FOREIGN KEY (thread_id) REFERENCES community_thread (id),
    CONSTRAINT ck_report_positive_ids
        CHECK (reporter_id > 0 AND target_id > 0),
    CONSTRAINT ck_report_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_report_target_type
        CHECK (target_type IN ('POST', 'COMMENT', 'THREAD_MESSAGE')),
    CONSTRAINT ck_report_reason_code
        CHECK (reason_code IS NULL OR reason_code IN ('SPAM', 'ABUSE', 'INAPPROPRIATE', 'PRIVACY', 'ETC')),
    CONSTRAINT ck_report_thread_message_fields
        CHECK (
            (target_type = 'THREAD_MESSAGE'
                AND thread_id IS NOT NULL
                AND thread_id > 0
                AND reason_code IS NOT NULL)
            OR
            (target_type IN ('POST', 'COMMENT') AND thread_id IS NULL AND reason_code IS NULL)
        )
);

COMMENT ON COLUMN report.reporter_id IS '신고자 member.id';

CREATE INDEX idx_report_thread_message_inbox
    ON report (status, created_at DESC, id DESC)
    WHERE target_type = 'THREAD_MESSAGE';

CREATE INDEX idx_report_thread_message_thread
    ON report (thread_id, created_at DESC, id DESC)
    WHERE target_type = 'THREAD_MESSAGE';
