CREATE TABLE community_thread
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_room_id                  BIGINT                                  NOT NULL,
    title                         VARCHAR(80)                             NOT NULL,
    description                   VARCHAR(500),
    category                      VARCHAR(20)                             NOT NULL,
    icon                          VARCHAR(128)                            NOT NULL,
    creator_member_id             BIGINT                                  NOT NULL,
    last_message_id               BIGINT,
    last_message_preview          VARCHAR(2000),
    last_message_sender_member_id BIGINT,
    last_message_created_at       TIMESTAMP WITH TIME ZONE,
    last_activity_at              TIMESTAMP WITH TIME ZONE                NOT NULL,
    deleted_at                    TIMESTAMP WITH TIME ZONE,
    created_at                    TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                    TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_community_thread PRIMARY KEY (id),
    CONSTRAINT uq_community_thread_chat_room UNIQUE (chat_room_id),
    CONSTRAINT ck_community_thread_category
        CHECK (category IN ('STUDY', 'QNA', 'PROJECT', 'FREE')),
    CONSTRAINT ck_community_thread_positive_ids
        CHECK (chat_room_id > 0 AND creator_member_id > 0),
    CONSTRAINT ck_community_thread_title
        CHECK (char_length(btrim(title)) BETWEEN 1 AND 80),
    CONSTRAINT ck_community_thread_description
        CHECK (description IS NULL OR char_length(description) <= 500),
    CONSTRAINT ck_community_thread_icon
        CHECK (char_length(btrim(icon)) BETWEEN 1 AND 32),
    CONSTRAINT ck_community_thread_last_message
        CHECK (
            (last_message_id IS NULL
                AND last_message_preview IS NULL
                AND last_message_sender_member_id IS NULL
                AND last_message_created_at IS NULL)
            OR
            (last_message_id IS NOT NULL
                AND last_message_id > 0
                AND last_message_preview IS NOT NULL
                AND last_message_sender_member_id IS NOT NULL
                AND last_message_sender_member_id > 0
                AND last_message_created_at IS NOT NULL)
        )
);

CREATE INDEX idx_community_thread_active_list
    ON community_thread (deleted_at, last_activity_at DESC, id DESC);

CREATE TABLE community_thread_member
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thread_id    BIGINT                                  NOT NULL,
    member_id    BIGINT                                  NOT NULL,
    role         VARCHAR(20)                             NOT NULL,
    state        VARCHAR(20)                             NOT NULL,
    joined_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    left_at      TIMESTAMP WITH TIME ZONE,
    is_pinned    BOOLEAN                                 NOT NULL DEFAULT FALSE,
    is_muted     BOOLEAN                                 NOT NULL DEFAULT FALSE,
    unread_count BIGINT                                  NOT NULL DEFAULT 0,
    created_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_community_thread_member PRIMARY KEY (id),
    CONSTRAINT uq_community_thread_member_thread_member UNIQUE (thread_id, member_id),
    CONSTRAINT fk_community_thread_member_thread
        FOREIGN KEY (thread_id) REFERENCES community_thread (id),
    CONSTRAINT ck_community_thread_member_positive_ids
        CHECK (thread_id > 0 AND member_id > 0),
    CONSTRAINT ck_community_thread_member_role
        CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER')),
    CONSTRAINT ck_community_thread_member_state
        CHECK (state IN ('ACTIVE', 'LEFT', 'KICKED')),
    CONSTRAINT ck_community_thread_member_unread_count
        CHECK (unread_count >= 0),
    CONSTRAINT ck_community_thread_member_lifecycle
        CHECK (
            (state = 'ACTIVE' AND left_at IS NULL)
            OR (state IN ('LEFT', 'KICKED') AND left_at IS NOT NULL)
        )
);

CREATE INDEX idx_community_thread_member_thread_state
    ON community_thread_member (thread_id, state, role, member_id);

CREATE INDEX idx_community_thread_member_member_state
    ON community_thread_member (member_id, state, is_pinned, thread_id);

CREATE INDEX idx_community_thread_member_member_unread
    ON community_thread_member (member_id, thread_id)
    WHERE state = 'ACTIVE' AND unread_count > 0;

CREATE UNIQUE INDEX uq_community_thread_member_active_owner
    ON community_thread_member (thread_id)
    WHERE role = 'OWNER' AND state = 'ACTIVE';

ALTER TABLE report
    ADD COLUMN thread_id BIGINT,
    ADD COLUMN reason_code VARCHAR(32);

ALTER TABLE report
    DROP CONSTRAINT report_target_type_check;

ALTER TABLE report
    ADD CONSTRAINT report_target_type_check
        CHECK (target_type IN ('POST', 'COMMENT', 'THREAD_MESSAGE')),
    ADD CONSTRAINT fk_report_community_thread
        FOREIGN KEY (thread_id) REFERENCES community_thread (id),
    ADD CONSTRAINT ck_report_reason_code
        CHECK (reason_code IS NULL OR reason_code IN ('SPAM', 'ABUSE', 'INAPPROPRIATE', 'PRIVACY', 'ETC')),
    ADD CONSTRAINT ck_report_thread_message_fields
        CHECK (
            (target_type = 'THREAD_MESSAGE'
                AND thread_id IS NOT NULL
                AND thread_id > 0
                AND reason_code IS NOT NULL)
            OR
            (target_type IN ('POST', 'COMMENT') AND thread_id IS NULL AND reason_code IS NULL)
        );

CREATE UNIQUE INDEX uq_report_thread_message_reporter_target
    ON report (reporter_id, target_id)
    WHERE target_type = 'THREAD_MESSAGE';

CREATE INDEX idx_report_thread_message_inbox
    ON report (status, created_at DESC, id DESC)
    WHERE target_type = 'THREAD_MESSAGE';

CREATE INDEX idx_report_thread_message_thread
    ON report (thread_id, created_at DESC, id DESC)
    WHERE target_type = 'THREAD_MESSAGE';
