CREATE TABLE public.fcm_outbox
(
    id           bigint                      NOT NULL,
    member_id    bigint                      NOT NULL,
    event_type   varchar(50)                 NOT NULL,
    payload      text,
    status       varchar(20)                 NOT NULL DEFAULT 'PENDING',
    retry_count  int                         NOT NULL DEFAULT 0,
    created_at   timestamp(6) with time zone NOT NULL,
    updated_at   timestamp(6) with time zone NOT NULL,
    processed_at timestamp(6) with time zone
);

ALTER TABLE public.fcm_outbox
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.fcm_outbox_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

ALTER TABLE ONLY public.fcm_outbox
    ADD CONSTRAINT fcm_outbox_pkey PRIMARY KEY (id);

CREATE INDEX idx_fcm_outbox_status ON public.fcm_outbox (status);
