-- 학교와 대상 기수별 모집 생명주기를 관리하는 최상위 Season을 생성한다.
CREATE TABLE public.recruiting_season
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    gisu_id    BIGINT                                  NOT NULL,
    school_id  BIGINT                                  NOT NULL,
    memo       TEXT,
    CONSTRAINT pk_recruiting_season PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_season_gisu_school UNIQUE (gisu_id, school_id)
);

-- Season이 모집할 수 있는 track별 목표 인원을 저장한다. INFRA_PLUS는 모집 대상에서 제외한다.
CREATE TABLE public.recruiting_season_track_quota
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_season_id BIGINT                                  NOT NULL,
    track                VARCHAR(255)                            NOT NULL,
    target_count         INTEGER                                 NOT NULL,
    CONSTRAINT pk_recruiting_season_track_quota PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_season_track_quota_season_track UNIQUE (recruiting_season_id, track),
    CONSTRAINT fk_recruiting_season_track_quota_season
        FOREIGN KEY (recruiting_season_id) REFERENCES public.recruiting_season (id),
    CONSTRAINT recruiting_season_track_quota_track_check CHECK (
        track IN ('PLAN', 'DESIGN', 'WEB_PRODUCT_ENGINEER', 'MOBILE_PRODUCT_ENGINEER')
    ),
    CONSTRAINT recruiting_season_track_quota_target_count_check CHECK (target_count >= 0)
);

-- 본모집과 추가모집 차수의 모집 track, 전형 일정, 공지 및 연락처를 저장한다.
CREATE TABLE public.recruiting_round
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                   TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                   TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_season_id         BIGINT                                  NOT NULL,
    type                         VARCHAR(255)                            NOT NULL,
    round_no                     INTEGER                                 NOT NULL,
    title                        VARCHAR(100)                            NOT NULL,
    status                       VARCHAR(255)                            NOT NULL,
    recruitable_tracks           TEXT[]                                  NOT NULL DEFAULT ARRAY[]::TEXT[],
    second_choice_enabled        BOOLEAN                                 NOT NULL DEFAULT FALSE,
    document_start_at            TIMESTAMP WITH TIME ZONE,
    document_end_at              TIMESTAMP WITH TIME ZONE,
    document_result_published_at TIMESTAMP WITH TIME ZONE,
    interview_required           BOOLEAN                                 NOT NULL DEFAULT FALSE,
    interview_start_at           TIMESTAMP WITH TIME ZONE,
    interview_end_at             TIMESTAMP WITH TIME ZONE,
    final_result_published_at     TIMESTAMP WITH TIME ZONE,
    availability_form_id         BIGINT,
    announcement                 TEXT,
    contact_text                 TEXT,
    CONSTRAINT pk_recruiting_round PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_round_season_type_no UNIQUE (recruiting_season_id, type, round_no),
    CONSTRAINT fk_recruiting_round_season
        FOREIGN KEY (recruiting_season_id) REFERENCES public.recruiting_season (id),
    CONSTRAINT recruiting_round_type_check CHECK (type IN ('REGULAR', 'ADDITIONAL')),
    CONSTRAINT recruiting_round_status_check CHECK (status IN ('DRAFT', 'OPEN', 'CLOSED')),
    CONSTRAINT recruiting_round_no_check CHECK (round_no >= 1),
    CONSTRAINT recruiting_round_recruitable_tracks_check CHECK (
        cardinality(recruitable_tracks) = 0
        OR (
            recruitable_tracks <@ ARRAY[
                'PLAN',
                'DESIGN',
                'WEB_PRODUCT_ENGINEER',
                'MOBILE_PRODUCT_ENGINEER'
            ]::TEXT[]
            AND cardinality(array_positions(recruitable_tracks, 'PLAN')) <= 1
            AND cardinality(array_positions(recruitable_tracks, 'DESIGN')) <= 1
            AND cardinality(array_positions(recruitable_tracks, 'WEB_PRODUCT_ENGINEER')) <= 1
            AND cardinality(array_positions(recruitable_tracks, 'MOBILE_PRODUCT_ENGINEER')) <= 1
        )
    ),
    CONSTRAINT recruiting_round_schedule_check CHECK (
        (
            document_start_at IS NULL
            AND document_end_at IS NULL
            AND document_result_published_at IS NULL
            AND interview_start_at IS NULL
            AND interview_end_at IS NULL
            AND final_result_published_at IS NULL
            AND availability_form_id IS NULL
            AND NOT interview_required
        )
        OR (
            document_start_at IS NOT NULL
            AND document_end_at IS NOT NULL
            AND document_result_published_at IS NOT NULL
            AND final_result_published_at IS NOT NULL
            AND document_start_at < document_end_at
            AND document_end_at <= document_result_published_at
            AND (
                (
                    interview_required
                    AND interview_start_at IS NOT NULL
                    AND interview_end_at IS NOT NULL
                    AND document_result_published_at <= interview_start_at
                    AND interview_start_at < interview_end_at
                    AND interview_end_at <= final_result_published_at
                )
                OR (
                    NOT interview_required
                    AND interview_start_at IS NULL
                    AND interview_end_at IS NULL
                    AND availability_form_id IS NULL
                    AND document_result_published_at <= final_result_published_at
                )
            )
        )
    )
);

-- 각 Round가 지원서 작성에 사용할 Form 하나와 Recruiting 내부 게시 상태를 연결한다.
CREATE TABLE public.recruiting_application_form
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_round_id  BIGINT                                  NOT NULL,
    form_id              BIGINT                                  NOT NULL,
    status               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_recruiting_application_form PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_application_form_round UNIQUE (recruiting_round_id),
    CONSTRAINT fk_recruiting_application_form_round
        FOREIGN KEY (recruiting_round_id) REFERENCES public.recruiting_round (id),
    CONSTRAINT recruiting_application_form_status_check CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'CLOSED')
    )
);

-- Form section을 공통 또는 track 전용 질문으로 분류해 지원자별 응답 범위를 결정한다.
CREATE TABLE public.recruiting_form_section_policy
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                      TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                      TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_application_form_id BIGINT                                  NOT NULL,
    form_section_id                 BIGINT                                  NOT NULL,
    type                            VARCHAR(255)                            NOT NULL,
    track                           VARCHAR(255),
    CONSTRAINT pk_recruiting_form_section_policy PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_form_section_policy_form_section UNIQUE (form_section_id),
    CONSTRAINT fk_recruiting_form_section_policy_application_form
        FOREIGN KEY (recruiting_application_form_id) REFERENCES public.recruiting_application_form (id),
    CONSTRAINT recruiting_form_section_policy_type_check CHECK (type IN ('COMMON', 'TRACK')),
    CONSTRAINT recruiting_form_section_policy_track_check CHECK (
        (type = 'COMMON' AND track IS NULL)
        OR (
            type = 'TRACK'
            AND track IS NOT NULL
            AND track IN ('PLAN', 'DESIGN', 'WEB_PRODUCT_ENGINEER', 'MOBILE_PRODUCT_ENGINEER')
        )
    )
);

-- 지원자의 기본 정보, Form 응답 연결, 전형 상태와 등록 상태를 하나의 지원서로 저장한다.
CREATE TABLE public.recruiting_application
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                      TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                      TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_round_id             BIGINT                                  NOT NULL,
    recruiting_application_form_id  BIGINT                                  NOT NULL,
    form_response_id                BIGINT                                  NOT NULL,
    form_response_access_key        VARCHAR(128),
    applicant_member_id             BIGINT,
    applicant_name                  VARCHAR(100)                            NOT NULL,
    applicant_email                 VARCHAR(255)                            NOT NULL,
    first_choice                    VARCHAR(255)                            NOT NULL,
    second_choice                   VARCHAR(255),
    privacy_term_id                 BIGINT,
    privacy_agreed_at               TIMESTAMP WITH TIME ZONE,
    application_key                 VARCHAR(6)                              NOT NULL,
    accepted_track                  VARCHAR(255),
    status                          VARCHAR(255)                            NOT NULL,
    registration_status             VARCHAR(255)                            NOT NULL,
    submitted_at                    TIMESTAMP WITH TIME ZONE,
    status_changed_member_id        BIGINT,
    status_change_reason            VARCHAR(255),
    status_changed_at               TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_recruiting_application PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_application_form_response UNIQUE (form_response_id),
    CONSTRAINT uk_recruiting_application_round_email UNIQUE (recruiting_round_id, applicant_email),
    CONSTRAINT uk_recruiting_application_round_member UNIQUE (recruiting_round_id, applicant_member_id),
    CONSTRAINT uk_recruiting_application_email_key UNIQUE (applicant_email, application_key),
    CONSTRAINT fk_recruiting_application_round
        FOREIGN KEY (recruiting_round_id) REFERENCES public.recruiting_round (id),
    CONSTRAINT fk_recruiting_application_form
        FOREIGN KEY (recruiting_application_form_id) REFERENCES public.recruiting_application_form (id),
    CONSTRAINT recruiting_application_name_check CHECK (
        applicant_name <> '' AND applicant_name !~ '[[:space:]]'
    ),
    CONSTRAINT recruiting_application_email_normalized_check CHECK (
        applicant_email = LOWER(BTRIM(applicant_email))
        AND LENGTH(applicant_email) <= 254
        AND LENGTH(SPLIT_PART(applicant_email, '@', 1)) <= 64
        AND applicant_email ~
            '^[a-z0-9!#$%&''*+/=?^_`{|}~-]+([.][a-z0-9!#$%&''*+/=?^_`{|}~-]+)*@[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?([.][a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$'
    ),
    CONSTRAINT recruiting_application_key_check CHECK (application_key ~ '^[A-Z0-9]{6}$'),
    CONSTRAINT recruiting_application_choice_track_check CHECK (
        first_choice IN ('PLAN', 'DESIGN', 'WEB_PRODUCT_ENGINEER', 'MOBILE_PRODUCT_ENGINEER')
        AND (
            second_choice IS NULL
            OR second_choice IN ('PLAN', 'DESIGN', 'WEB_PRODUCT_ENGINEER', 'MOBILE_PRODUCT_ENGINEER')
        )
        AND second_choice IS DISTINCT FROM first_choice
    ),
    CONSTRAINT recruiting_application_privacy_check CHECK (
        (privacy_term_id IS NULL AND privacy_agreed_at IS NULL)
        OR (privacy_term_id IS NOT NULL AND privacy_agreed_at IS NOT NULL)
    ),
    CONSTRAINT recruiting_application_identity_mode_check CHECK (
        (
            applicant_member_id IS NOT NULL
            AND form_response_access_key IS NULL
        )
        OR (
            applicant_member_id IS NULL
            AND form_response_access_key IS NOT NULL
            AND BTRIM(form_response_access_key) <> ''
            AND privacy_term_id IS NOT NULL
            AND privacy_agreed_at IS NOT NULL
        )
    ),
    CONSTRAINT recruiting_application_accepted_track_check CHECK (
        accepted_track IS NULL
        OR accepted_track = first_choice
        OR accepted_track = second_choice
    ),
    CONSTRAINT recruiting_application_status_check CHECK (
        status IN (
            'DRAFT',
            'SUBMITTED',
            'DOCUMENT_FAILED',
            'INTERVIEW_ASSIGNED',
            'INTERVIEW_SKIPPED',
            'FINAL_PASSED',
            'FINAL_FAILED',
            'CANCELLED'
        )
    ),
    CONSTRAINT recruiting_application_registration_status_check CHECK (
        registration_status IN ('NOT_READY', 'READY', 'REGISTERED')
    ),
    CONSTRAINT recruiting_application_final_pass_track_check CHECK (
        status <> 'FINAL_PASSED' OR accepted_track IS NOT NULL
    ),
    CONSTRAINT recruiting_application_registration_lifecycle_check CHECK (
        registration_status = 'NOT_READY'
        OR (status = 'FINAL_PASSED' AND accepted_track IS NOT NULL)
    )
);

-- Round에 등록된 평가자가 서류와 면접 평가에 모두 참여할 수 있도록 whitelist를 저장한다.
CREATE TABLE public.recruiting_round_evaluator
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_round_id  BIGINT                                  NOT NULL,
    member_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_recruiting_round_evaluator PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_round_evaluator_round_member UNIQUE (recruiting_round_id, member_id),
    CONSTRAINT fk_recruiting_round_evaluator_round
        FOREIGN KEY (recruiting_round_id) REFERENCES public.recruiting_round (id)
);

-- Round 전체 면접에서 공통으로 사용할 질문과 생성자·최종 변경자를 저장한다.
CREATE TABLE public.recruiting_round_interview_question
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                 TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                 TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_round_id        BIGINT                                  NOT NULL,
    content                    TEXT                                    NOT NULL,
    order_no                   INTEGER                                 NOT NULL,
    active                     BOOLEAN                                 NOT NULL DEFAULT TRUE,
    creator_member_id          BIGINT                                  NOT NULL,
    last_modified_by_member_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_recruiting_round_interview_question PRIMARY KEY (id),
    CONSTRAINT fk_recruiting_round_interview_question_round
        FOREIGN KEY (recruiting_round_id) REFERENCES public.recruiting_round (id),
    CONSTRAINT recruiting_round_interview_question_content_check CHECK (length(btrim(content)) > 0),
    CONSTRAINT recruiting_round_interview_question_order_no_check CHECK (order_no >= 0),
    CONSTRAINT recruiting_round_interview_question_creator_check CHECK (creator_member_id > 0),
    CONSTRAINT recruiting_round_interview_question_modifier_check CHECK (last_modified_by_member_id > 0)
);

-- 지원자별 면접에서 추가로 사용할 개별 질문을 저장한다.
CREATE TABLE public.recruiting_application_interview_question
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                 TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                 TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_application_id BIGINT                                  NOT NULL,
    content                    TEXT                                    NOT NULL,
    order_no                   INTEGER                                 NOT NULL,
    active                     BOOLEAN                                 NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_recruiting_application_interview_question PRIMARY KEY (id),
    CONSTRAINT fk_recruiting_application_interview_question_application
        FOREIGN KEY (recruiting_application_id) REFERENCES public.recruiting_application (id),
    CONSTRAINT recruiting_application_interview_question_content_check CHECK (length(btrim(content)) > 0),
    CONSTRAINT recruiting_application_interview_question_order_no_check CHECK (order_no >= 0)
);

-- 평가자별 서류·면접 평가를 APPROVED 또는 REJECTED의 제출 완료 결과로 저장한다.
CREATE TABLE public.recruiting_application_evaluation
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                 TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                 TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_application_id BIGINT                                  NOT NULL,
    evaluator_member_id        BIGINT                                  NOT NULL,
    stage                      VARCHAR(255)                            NOT NULL,
    decision                   VARCHAR(255)                            NOT NULL,
    comment                    VARCHAR(2000),
    submitted_at               TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_recruiting_application_evaluation PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_application_evaluation_application_evaluator_stage
        UNIQUE (recruiting_application_id, evaluator_member_id, stage),
    CONSTRAINT fk_recruiting_application_evaluation_application
        FOREIGN KEY (recruiting_application_id) REFERENCES public.recruiting_application (id),
    CONSTRAINT recruiting_application_evaluation_evaluator_check CHECK (evaluator_member_id > 0),
    CONSTRAINT recruiting_application_evaluation_stage_check CHECK (stage IN ('DOCUMENT', 'INTERVIEW')),
    CONSTRAINT recruiting_application_evaluation_decision_check CHECK (decision IN ('APPROVED', 'REJECTED'))
);

-- 면접 가능 일정 요청부터 확정까지의 일정과 메일 발송·재시도 상태를 저장한다.
CREATE TABLE public.recruiting_interview_schedule
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                    TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at                    TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_application_id    BIGINT                                  NOT NULL,
    availability_form_response_id BIGINT,
    status                        VARCHAR(255)                            NOT NULL,
    starts_at                     TIMESTAMP WITH TIME ZONE,
    ends_at                       TIMESTAMP WITH TIME ZONE,
    location                      VARCHAR(255),
    contact_snapshot              VARCHAR(2000)                           NOT NULL,
    request_mail_status           VARCHAR(255)                            NOT NULL,
    request_mail_attempts         INTEGER                                 NOT NULL,
    request_mail_error            VARCHAR(2000),
    request_mail_sent_at          TIMESTAMP WITH TIME ZONE,
    confirmation_mail_status      VARCHAR(255)                            NOT NULL,
    confirmation_mail_attempts    INTEGER                                 NOT NULL,
    confirmation_mail_error       VARCHAR(2000),
    confirmation_mail_sent_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_recruiting_interview_schedule PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_interview_schedule_application UNIQUE (recruiting_application_id),
    CONSTRAINT fk_recruiting_interview_schedule_application
        FOREIGN KEY (recruiting_application_id) REFERENCES public.recruiting_application (id),
    CONSTRAINT recruiting_interview_schedule_status_check CHECK (
        status IN ('AVAILABILITY_REQUESTED', 'AVAILABILITY_SUBMITTED', 'CONFIRMED', 'CANCELLED')
    ),
    CONSTRAINT recruiting_interview_schedule_response_check CHECK (
        availability_form_response_id IS NULL OR availability_form_response_id > 0
    ),
    CONSTRAINT recruiting_interview_schedule_contact_check CHECK (BTRIM(contact_snapshot) <> ''),
    CONSTRAINT recruiting_interview_schedule_state_check CHECK (
        status = 'CANCELLED'
        OR (
            status = 'AVAILABILITY_REQUESTED'
            AND availability_form_response_id IS NULL
            AND starts_at IS NULL
            AND ends_at IS NULL
            AND location IS NULL
        )
        OR (
            status = 'AVAILABILITY_SUBMITTED'
            AND availability_form_response_id IS NOT NULL
            AND starts_at IS NULL
            AND ends_at IS NULL
            AND location IS NULL
        )
        OR (
            status = 'CONFIRMED'
            AND availability_form_response_id IS NOT NULL
            AND starts_at IS NOT NULL
            AND ends_at IS NOT NULL
            AND starts_at < ends_at
            AND location IS NOT NULL
            AND BTRIM(location) <> ''
        )
    ),
    CONSTRAINT recruiting_interview_schedule_mail_attempts_check CHECK (
        request_mail_attempts >= 0 AND confirmation_mail_attempts >= 0
    ),
    CONSTRAINT recruiting_interview_schedule_request_mail_status_check CHECK (
        request_mail_status IN ('PENDING', 'SENT', 'FAILED')
    ),
    CONSTRAINT recruiting_interview_schedule_confirmation_mail_status_check CHECK (
        confirmation_mail_status IN ('PENDING', 'SENT', 'FAILED')
    ),
    CONSTRAINT recruiting_interview_schedule_request_mail_shape_check CHECK (
        (request_mail_status = 'PENDING' AND request_mail_error IS NULL AND request_mail_sent_at IS NULL)
        OR (request_mail_status = 'SENT' AND request_mail_error IS NULL AND request_mail_sent_at IS NOT NULL)
        OR (
            request_mail_status = 'FAILED'
            AND request_mail_error IS NOT NULL
            AND BTRIM(request_mail_error) <> ''
            AND request_mail_sent_at IS NULL
        )
    ),
    CONSTRAINT recruiting_interview_schedule_confirmation_mail_shape_check CHECK (
        (
            confirmation_mail_status = 'PENDING'
            AND confirmation_mail_error IS NULL
            AND confirmation_mail_sent_at IS NULL
        )
        OR (
            confirmation_mail_status = 'SENT'
            AND confirmation_mail_error IS NULL
            AND confirmation_mail_sent_at IS NOT NULL
        )
        OR (
            confirmation_mail_status = 'FAILED'
            AND confirmation_mail_error IS NOT NULL
            AND BTRIM(confirmation_mail_error) <> ''
            AND confirmation_mail_sent_at IS NULL
        )
    )
);

-- 사용자가 구분하는 모집 제목은 같은 Season 안에서 대소문자와 무관하게 중복되지 않도록 한다.
CREATE UNIQUE INDEX uk_recruiting_round_season_title_ci
    ON public.recruiting_round (recruiting_season_id, LOWER(title));

-- Form별 section 정책 조회가 전체 정책 테이블을 순회하지 않도록 연결 인덱스를 생성한다.
CREATE INDEX ix_recruiting_form_section_policy_application_form
    ON public.recruiting_form_section_policy (recruiting_application_form_id);

-- 지원서 상태 기반 운영 조회를 지원한다.
CREATE INDEX ix_recruiting_application_status
    ON public.recruiting_application (status);

-- READY와 REGISTERED가 소비하는 track별 TO를 잠금·집계할 때 사용할 부분 인덱스를 생성한다.
CREATE INDEX ix_recruiting_application_quota_usage
    ON public.recruiting_application (recruiting_round_id, accepted_track, registration_status)
    WHERE registration_status IN ('READY', 'REGISTERED');

-- Round 공통 질문을 활성 여부와 표시 순서로 조회할 수 있도록 인덱스를 생성한다.
CREATE INDEX ix_recruiting_round_interview_question_round_active_order
    ON public.recruiting_round_interview_question (recruiting_round_id, active, order_no, id);

-- 지원자 개별 질문을 활성 여부와 표시 순서로 조회할 수 있도록 인덱스를 생성한다.
CREATE INDEX ix_recruiting_application_interview_question_application_active_order
    ON public.recruiting_application_interview_question (recruiting_application_id, active, order_no, id);

-- 지원서의 전형 단계별 평가 목록 조회를 지원한다.
CREATE INDEX ix_recruiting_application_evaluation_application_stage
    ON public.recruiting_application_evaluation (recruiting_application_id, stage);
