-- 감사 로그 테이블 생성
-- 일정 생성/수정, 출석 승인/신청, 회원가입/탈퇴 등 주요 액션에 대한 감사 로그 저장

CREATE TABLE public.audit_log
(
    id              bigint                      NOT NULL,
    domain          character varying(50)       NOT NULL,
    action          character varying(50)       NOT NULL,
    target_type     character varying(100)      NOT NULL,
    target_id       character varying(255),
    actor_member_id bigint,
    description     text,
    details         jsonb,
    ip_address      character varying(45),
    created_at      timestamp(6) with time zone NOT NULL
);

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);

CREATE INDEX idx_audit_log_domain_action ON public.audit_log (domain, action);
CREATE INDEX idx_audit_log_target ON public.audit_log (target_type, target_id);
CREATE INDEX idx_audit_log_actor ON public.audit_log (actor_member_id);
CREATE INDEX idx_audit_log_created_at ON public.audit_log (created_at);
