-- 데모데이 현장 투표 도메인 테이블을 생성한다.

-- 한 데모데이에서 투표는 1건이다. 투표창(opens_at ~ closes_at)과 투표 상태를 저장한다.
CREATE TABLE demoday_poll
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    gisu_id    BIGINT                                  NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    opens_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    closes_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_demoday_poll PRIMARY KEY (id),
    CONSTRAINT demoday_poll_status_check CHECK (status IN ('OPEN', 'CLOSED')),
    CONSTRAINT ck_demoday_poll_window CHECK ( opens_at < closes_at )
);

-- 데모데이 투표 대상 부스를 나타내는 테이블이다.
-- project_id가 NULL이면 UPMS에 없는 프로젝트이고, 이 경우에만 display_name을 사용한다.
CREATE TABLE demoday_booth
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE                NOT NULL,
    demoday_poll_id BIGINT                                  NOT NULL,
    project_id      BIGINT,
    display_name    VARCHAR(255),
    CONSTRAINT pk_demoday_booth PRIMARY KEY (id),
    CONSTRAINT fk_demoday_booth_poll
        FOREIGN KEY (demoday_poll_id) REFERENCES demoday_poll (id)
);

-- 외부인 입장 코드 레지스트리이다. 코드와 소셜 identity 를 해시로만 저장하고 이름 및 연락처는 저장하지 않는다.
-- bound_identity_hash는 최초 교환 시 한 번만 세팅되고 이후에는 불변이다.
CREATE TABLE demoday_entry_code
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE                NOT NULL,
    demoday_poll_id     BIGINT                                  NOT NULL,
    code_hash           VARCHAR(64)                             NOT NULL,
    bound_identity_hash VARCHAR(64),
    redeemed_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_demoday_entry_code PRIMARY KEY (id),
    CONSTRAINT uk_demoday_entry_code_hash UNIQUE (code_hash),
    CONSTRAINT fk_demoday_entry_code_poll
        FOREIGN KEY (demoday_poll_id) REFERENCES demoday_poll (id)
);

-- 개별 표를 저장하는 테이블이다.
-- append-only 이며 유일한 UPDATE는 어드민 권한으로 무효화(revoked_at) 하는 것 뿐이다.
CREATE TABLE demoday_vote
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE                NOT NULL,
    demoday_poll_id BIGINT                                  NOT NULL,
    member_id       BIGINT,
    entry_code_id   BIGINT,
    target_booth_id BIGINT                                  NOT NULL,
    revoked_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_demoday_vote PRIMARY KEY (id),
    CONSTRAINT ck_demoday_vote_identifier_xor
        CHECK ( (member_id IS NULL) <> (entry_code_id IS NULL) ),
    CONSTRAINT fk_demoday_vote_poll
        FOREIGN KEY (demoday_poll_id) REFERENCES demoday_poll (id),
    CONSTRAINT fk_demoday_vote_entry_code
        FOREIGN KEY (entry_code_id) REFERENCES demoday_entry_code (id),
    CONSTRAINT fk_demoday_vote_target_booth
        FOREIGN KEY (target_booth_id) REFERENCES demoday_booth (id)
);

-- 부스 방문 스탬프 저장하는 테이블이다.
CREATE TABLE demoday_stamp
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    member_id     BIGINT,
    entry_code_id BIGINT,
    booth_id      BIGINT                                  NOT NULL,
    revoked_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_demoday_stamp PRIMARY KEY (id),
    CONSTRAINT ck_demoday_stamp_identifier_xor
        CHECK ( (member_id IS NULL) <> (entry_code_id IS NULL)),
    CONSTRAINT fk_demoday_stamp_entry_code
        FOREIGN KEY (entry_code_id) REFERENCES demoday_entry_code (id),
    CONSTRAINT fk_demoday_stamp_booth
        FOREIGN KEY (booth_id) REFERENCES demoday_booth (id)
);

-- 1인 1표 제약을 둔다.(UMC 인원)
CREATE UNIQUE INDEX uk_demoday_vote_poll_member
    ON demoday_vote (demoday_poll_id, member_id) WHERE member_id IS NOT NULL;

-- 1인 1표 제약을 둔다.(외부인)
CREATE UNIQUE INDEX uk_demoday_vote_entry_code
    ON demoday_vote (entry_code_id) WHERE entry_code_id IS NOT NULL;

-- 부스 스탬프를 재스캔해도 중복 행이 생성되지 않도록 멱등성을 보장한다.(UMC 인원)
CREATE UNIQUE INDEX uk_demoday_stamp_member_booth
    ON demoday_stamp (member_id, booth_id) WHERE member_id IS NOT NULL;

-- 부스 스탬프를 재스캔해도 중복 행이 생성되지 않도록 멱등성을 보장한다.(외부인)
CREATE UNIQUE INDEX uk_demoday_stamp_entry_code_booth
    ON demoday_stamp (entry_code_id, booth_id) WHERE entry_code_id IS NOT NULL;

-- 한 사람(소셜 계정)이 투표당 코드를 하나만 바인딩 할 수 있도록 제한한다.
-- 분실된 인증 코드를 주워 1인 N투표를 하는 것을 방지하기 위한 제약이다.
-- demoday_vote의 UNIQUE(entry_code_id)와 합쳐져 1인당 1표를 제한한다.
-- 소셜 로그인 미도입 시에는 전 행이 NULL이기 때문에 인덱스가 비어버리게 되어 아무것도 제약하지 않게 된다.
CREATE UNIQUE INDEX uk_demoday_entry_code_identity
    ON demoday_entry_code (demoday_poll_id, bound_identity_hash) WHERE bound_identity_hash IS NOT NULL;

-- 인덱스를 설정하여 부스 목록 조회시 테이블 전체 행이 스캔되지 않도록 한다.
CREATE INDEX ix_demoday_booth_poll
    ON demoday_booth (demoday_poll_id);

-- 부스별 득표 집계를 위한 인덱스이다.
CREATE INDEX ix_demoday_vote_poll_booth
    ON demoday_vote (demoday_poll_id, target_booth_id);

