CREATE TABLE public.recruiting_interview_session
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE                NOT NULL,
    recruiting_round_id   BIGINT                                  NOT NULL,
    name                  VARCHAR(100)                            NOT NULL,
    starts_at             TIMESTAMP WITH TIME ZONE                NOT NULL,
    ends_at               TIMESTAMP WITH TIME ZONE                NOT NULL,
    slot_duration_minutes INTEGER                                 NOT NULL,
    mode                  VARCHAR(255)                            NOT NULL,
    location              VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_recruiting_interview_session PRIMARY KEY (id),
    CONSTRAINT fk_recruiting_interview_session_round
        FOREIGN KEY (recruiting_round_id) REFERENCES public.recruiting_round (id),
    CONSTRAINT recruiting_interview_session_name_check CHECK (BTRIM(name) <> ''),
    CONSTRAINT recruiting_interview_session_period_check CHECK (
        starts_at < ends_at
        AND MOD(EXTRACT(EPOCH FROM starts_at), 900) = 0
        AND MOD(EXTRACT(EPOCH FROM ends_at), 900) = 0
    ),
    CONSTRAINT recruiting_interview_session_slot_duration_check CHECK (
        slot_duration_minutes > 0 AND MOD(slot_duration_minutes, 15) = 0
    ),
    CONSTRAINT recruiting_interview_session_mode_check CHECK (mode IN ('ONLINE', 'OFFLINE')),
    CONSTRAINT recruiting_interview_session_location_check CHECK (BTRIM(location) <> '')
);

CREATE INDEX idx_recruiting_interview_session_round
    ON public.recruiting_interview_session (recruiting_round_id);

ALTER TABLE public.recruiting_interview_schedule
    ADD COLUMN interview_session_id BIGINT,
    ADD CONSTRAINT fk_recruiting_interview_schedule_session
        FOREIGN KEY (interview_session_id) REFERENCES public.recruiting_interview_session (id);

CREATE UNIQUE INDEX uk_recruiting_interview_schedule_confirmed_session_start
    ON public.recruiting_interview_schedule (interview_session_id, starts_at)
    WHERE status = 'CONFIRMED' AND interview_session_id IS NOT NULL;
