CREATE TABLE public.recruiting_chapter_quota
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    gisu_id            BIGINT                                  NOT NULL,
    chapter_id         BIGINT                                  NOT NULL,
    total_target_count INTEGER                                 NOT NULL,
    CONSTRAINT pk_recruiting_chapter_quota PRIMARY KEY (id),
    CONSTRAINT uk_recruiting_chapter_quota_gisu_chapter UNIQUE (gisu_id, chapter_id),
    CONSTRAINT recruiting_chapter_quota_total_target_count_check CHECK (total_target_count >= 0)
);
