create table attendance_record
(
    id                  bigint generated by default as identity
        primary key,
    attendance_sheet_id bigint       not null,
    checked_at          timestamp(6),
    confirmed_at        timestamp(6),
    confirmed_by        bigint,
    member_id           bigint       not null,
    memo                varchar(500),
    status              varchar(255) not null
        constraint attendance_record_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'PRESENT'::character varying, 'PRESENT_PENDING'::character varying, 'LATE'::character varying, 'LATE_PENDING'::character varying, 'ABSENT'::character varying, 'EXCUSED'::character varying, 'EXCUSED_PENDING'::character varying])::text[]))
    );


create table attendance_sheet
(
    id                     bigint generated by default as identity
        primary key,
    active                 boolean      not null,
    requires_approval      boolean      not null,
    schedule_id            bigint       not null,
    end_time               timestamp(6) not null,
    late_threshold_minutes integer      not null,
    start_time             timestamp(6) not null
);


create table challenger
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    gisu_id    bigint                      not null,
    member_id  bigint                      not null,
    part       varchar(255)                not null
        constraint challenger_part_check
            check ((part)::text = ANY
        ((ARRAY ['PLAN'::character varying, 'DESIGN'::character varying, 'WEB'::character varying, 'IOS'::character varying, 'ANDROID'::character varying, 'SPRINGBOOT'::character varying, 'NODEJS'::character varying])::text[])),
    status     varchar(255)                not null
        constraint challenger_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'GRADUATED'::character varying, 'EXPELLED'::character varying, 'WITHDRAWN'::character varying])::text[]))
);



create table challenger_point
(
    id            bigint generated by default as identity
        primary key,
    description   varchar(200),
    point         varchar(255) not null
        constraint challenger_point_point_check
            check ((point)::text = ANY
        ((ARRAY ['BEST_WORKBOOK'::character varying, 'WARNING'::character varying, 'OUT'::character varying])::text[])),
    challenger_id bigint       not null
        constraint fk3j6c463flsyfd1mt8hip0xuvg
            references challenger
);

create table challenger_role
(
    id                bigint generated by default as identity
        primary key,
    role_type         varchar(255) not null
        constraint challenger_role_role_type_check
            check ((role_type)::text = ANY
        ((ARRAY ['CENTRAL_PRESIDENT'::character varying, 'CENTRAL_VICE_PRESIDENT'::character varying, 'CENTRAL_DIRECTOR'::character varying, 'CENTRAL_MANAGER'::character varying, 'CENTRAL_PART_LEADER'::character varying, 'CHAPTER_LEADER'::character varying, 'CHAPTER_STAFF'::character varying, 'SCHOOL_PRESIDENT'::character varying, 'SCHOOL_VICE_PRESIDENT'::character varying, 'SCHOOL_PART_LEADER'::character varying, 'SCHOOL_STAFF'::character varying, 'CHALLENGER'::character varying])::text[])),
    gisu_id           bigint       not null,
    leading_part      varchar(255)
        constraint challenger_role_leading_part_check
            check ((leading_part)::text = ANY
                   ((ARRAY ['PLAN'::character varying, 'DESIGN'::character varying, 'WEB'::character varying, 'IOS'::character varying, 'ANDROID'::character varying, 'SPRINGBOOT'::character varying, 'NODEJS'::character varying])::text[])),
    organization_id   bigint       not null,
    organization_type varchar(255) not null
        constraint challenger_role_organization_type_check
            check ((organization_type)::text = ANY
                   ((ARRAY ['CENTRAL'::character varying, 'CHAPTER'::character varying, 'SCHOOL'::character varying])::text[])),
    challenger_id     bigint       not null
        constraint fkhdc3ufdpgchr24oim9xrcracv
            references challenger
);

create table challenger_workbook
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone not null,
    best_reason          text,
    challenger_id        bigint                      not null,
    feedback             text,
    original_workbook_id bigint                      not null,
    schedule_id          bigint                      not null,
    status               varchar(255)                not null
        constraint challenger_workbook_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'SUBMITTED'::character varying, 'PASS'::character varying, 'FAIL'::character varying, 'BEST'::character varying])::text[])),
    submission           text
);


create table challenger_mission
(
    id                     bigint generated by default as identity
        primary key,
    created_at             timestamp(6) with time zone not null,
    updated_at             timestamp(6) with time zone not null,
    submission             text,
    workbook_mission_id    bigint                      not null,
    challenger_workbook_id bigint                      not null
        constraint fk48bd420ph229fccdgtsdaoxmj
            references challenger_workbook
);


create table comment
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    challenger_id bigint                      not null,
    content       text                        not null,
    parent_id     bigint,
    post_id       bigint                      not null
);


create table comment_like
(
    comment_id    bigint not null
        constraint fkqlv8phl1ibeh0efv4dbn3720p
            references comment,
    challenger_id bigint
);


create table curriculum
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    gisu_id    bigint                      not null,
    part       varchar(255)                not null
        constraint curriculum_part_check
            check ((part)::text = ANY
        ((ARRAY ['PLAN'::character varying, 'DESIGN'::character varying, 'WEB'::character varying, 'IOS'::character varying, 'ANDROID'::character varying, 'SPRINGBOOT'::character varying, 'NODEJS'::character varying])::text[])),
    title      varchar(255)                not null
);


create table email_verification
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    code        varchar(10)                 not null,
    email       varchar(200)                not null,
    expires_at  timestamp(6) with time zone not null,
    is_verified boolean                     not null,
    token       varchar(100)                not null,
    verified_at timestamp(6) with time zone,
    verified_by varchar(30)
);


create table file_metadata
(
    id                 varchar(255)                not null
        primary key,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    category           varchar(50)                 not null
        constraint file_metadata_category_check
            check ((category)::text = ANY
        ((ARRAY ['PROFILE_IMAGE'::character varying, 'POST_IMAGE'::character varying, 'POST_ATTACHMENT'::character varying, 'NOTICE_ATTACHMENT'::character varying, 'WORKBOOK_SUBMISSION'::character varying, 'ETC'::character varying])::text[])),
    content_type       varchar(100)                not null,
    file_size          bigint                      not null,
    is_uploaded        boolean                     not null,
    original_file_name varchar(255)                not null,
    storage_key        varchar(500)                not null
        constraint uk9dyihdja5sr0lm43v09dsnlyh
            unique,
    storage_provider   varchar(50)                 not null
        constraint file_metadata_storage_provider_check
            check ((storage_provider)::text = ANY
                   ((ARRAY ['AWS_S3'::character varying, 'GOOGLE_CLOUD_STORAGE'::character varying])::text[])),
    uploaded_member_id bigint
);


create table form
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6) with time zone not null,
    updated_at        timestamp(6) with time zone not null,
    created_member_id bigint                      not null,
    description       varchar(500),
    status            varchar(255)                not null
        constraint form_status_check
            check ((status)::text = ANY ((ARRAY ['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])),
    title             varchar(255)
);

create table form_response
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone not null,
    respondent_member_id bigint                      not null,
    status               varchar(255)                not null
        constraint form_response_status_check
            check ((status)::text = ANY ((ARRAY ['DRAFT'::character varying, 'SUBMITTED'::character varying])::text[])),
    submitted_at         timestamp(6) with time zone,
    submitted_ip         varchar(255),
    form_id              bigint                      not null
        constraint fk4sed41etq9jpqi0pskh7yukrv
            references form
);

create table form_section
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    description varchar(500),
    order_no    integer,
    target_key  varchar(50),
    title       varchar(255)                not null,
    type        varchar(255)                not null
        constraint form_section_type_check
            check ((type)::text = ANY ((ARRAY ['DEFAULT'::character varying, 'CUSTOM'::character varying])::text[])),
    form_id     bigint                      not null
        constraint fkpvynqwi2t1wrw3wv1imaidi8s
            references form
);


create table gisu
(
    id         bigint generated by default as identity
        primary key,
    end_at     timestamp(6),
    generation bigint,
    is_active  boolean,
    start_at   timestamp(6)
);


create table central_organization
(
    id      bigint generated by default as identity
        primary key,
    name    varchar(255),
    gisu_id bigint
        constraint fk2abyl3i2l2esjexkdlqg1lfyu
            references gisu
);



create table chapter
(
    id      bigint generated by default as identity
        primary key,
    name    varchar(255),
    gisu_id bigint
        constraint fkbhht5p1907cjerhqptxmkd5j8
            references gisu
);



create table member
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) with time zone not null,
    updated_at       timestamp(6) with time zone not null,
    email            varchar(100)                not null,
    name             varchar(30)                 not null,
    nickname         varchar(20)                 not null,
    profile_image_id varchar(255),
    school_id        bigint,
    status           varchar(20)                 not null
        constraint member_status_check
            check ((status)::text = ANY
        ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying, 'WITHDRAWN'::character varying])::text[]))
    );



create table fcm_token
(
    id        bigint generated by default as identity
        primary key,
    fcm_token text,
    member_id bigint not null
        constraint ukbkc4qj70rm42usijun58k0gi
            unique
        constraint fkf1rbjf8lle4r2in6ovkcgl0w8
            references member
);

create table member_oauth
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone not null,
    member_id      bigint                      not null,
    oauth_provider varchar(20)                 not null
        constraint member_oauth_oauth_provider_check
            check ((oauth_provider)::text = ANY
        ((ARRAY ['GOOGLE'::character varying, 'APPLE'::character varying, 'KAKAO'::character varying])::text[])),
    provider_id    varchar(512)                not null,
    constraint uk_member_oauth_provider_provider_id
        unique (oauth_provider, provider_id)
);


create table notice
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone not null,
    author_challenger_id bigint                      not null,
    content              varchar(255)                not null,
    notified_at          timestamp(6) with time zone,
    organization_ids     bigint[],
    scope                varchar(255)
        constraint notice_scope_check
            check ((scope)::text = ANY
        ((ARRAY ['MANAGER_NOTI'::character varying, 'PART'::character varying, 'CHAPTER'::character varying, 'SCHOOL'::character varying])::text[])),
    should_notify        boolean                     not null,
    target_gisu_id       bigint,
    target_parts         character varying[],
    target_roles         character varying[],
    title                varchar(255)                not null
);

create table notice_image
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    display_order integer                     not null,
    image_id      varchar(255)                not null,
    notice_id     bigint                      not null
        constraint fk13h2d99jqpw7xnaj5w1crvv8m
            references notice
);

create table notice_link
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    display_order integer                     not null,
    link          varchar(255)                not null,
    notice_id     bigint                      not null
        constraint fkffr7h4dyleo02gf9mtda2qg0p
            references notice
);

create table notice_read
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    challenger_id bigint                      not null,
    notice_id     bigint                      not null
        constraint fkfadagonkeggnjqyuy10d4qego
            references notice
);

create table notice_vote
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    display_order integer                     not null,
    vote_id       bigint                      not null,
    notice_id     bigint                      not null
        constraint fkp6as401tgeia8hn1uo2de199f
            references notice
);


create table original_workbook
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    description   varchar(255),
    end_date      date                        not null,
    mission_type  varchar(255)                not null
        constraint original_workbook_mission_type_check
            check ((mission_type)::text = ANY
        ((ARRAY ['LINK'::character varying, 'MEMO'::character varying, 'PLAIN'::character varying])::text[])),
    released_at   timestamp(6),
    start_date    date                        not null,
    title         varchar(255)                not null,
    week_no       integer                     not null,
    workbook_url  varchar(255),
    curriculum_id bigint                      not null
        constraint fk9mrmn4qk5lpxnhordx9jx0bdd
            references curriculum
);

create table post
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) with time zone not null,
    updated_at       timestamp(6) with time zone not null,
    anonymous        boolean                     not null,
    category         varchar(255)                not null
        constraint post_category_check
            check ((category)::text = ANY
        ((ARRAY ['LIGHTNING'::character varying, 'HABIT'::character varying, 'QUESTION'::character varying, 'INFORMATION'::character varying, 'ASK'::character varying, 'FREE'::character varying])::text[])),
    content          text                        not null,
    location         varchar(255),
    max_participants integer,
    meet_at          timestamp(6),
    region           varchar(255)                not null,
    title            varchar(255)                not null
);


create table post_like
(
    post_id       bigint not null
        constraint fkj7iy0k7n3d0vkh8o7ibjna884
            references post,
    challenger_id bigint
);


create table question
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp(6) with time zone not null,
    updated_at      timestamp(6) with time zone not null,
    is_required     boolean                     not null,
    order_no        integer                     not null,
    question_text   varchar(500)                not null,
    type            varchar(255)                not null
        constraint question_type_check
            check ((type)::text = ANY
        ((ARRAY ['SHORT_TEXT'::character varying, 'LONG_TEXT'::character varying, 'RADIO'::character varying, 'CHECKBOX'::character varying, 'DROPDOWN'::character varying, 'SCHEDULE'::character varying, 'PORTFOLIO'::character varying, 'PREFERRED_PART'::character varying])::text[])),
    form_section_id bigint                      not null
        constraint fk30lyi8qkalpwcjew60oahaa99
            references form_section
);


create table question_option
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    content     varchar(255)                not null,
    is_other    boolean                     not null,
    order_no    integer                     not null,
    question_id bigint
        constraint fkmmdv54rmm5hkgxbn1008ix87n
            references question
);

create table recruitment
(
    id                       bigint generated by default as identity
        primary key,
    created_at               timestamp(6) with time zone not null,
    updated_at               timestamp(6) with time zone not null,
    form_id                  bigint                      not null,
    gisu_id                  bigint,
    interview_time_table     jsonb,
    max_preferred_part_count integer,
    notice_content           varchar(255),
    notice_title             varchar(255),
    published_at             timestamp(6) with time zone,
    school_id                bigint,
    status                   varchar(255)
        constraint recruitment_status_check
            check ((status)::text = ANY ((ARRAY ['DRAFT'::character varying, 'PUBLISHED'::character varying])::text[])),
    title                    varchar(255)
);


create table application
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6) with time zone not null,
    updated_at          timestamp(6) with time zone not null,
    applicant_member_id bigint                      not null,
    doc_score           integer,
    final_score         integer,
    form_response_id    bigint                      not null,
    interview_score     integer,
    status              varchar(255)                not null
        constraint application_status_check
            check ((status)::text = ANY
        ((ARRAY ['APPLIED'::character varying, 'DOC_PASSED'::character varying, 'DOC_FAILED'::character varying, 'INTERVIEW_SCHEDULED'::character varying, 'INTERVIEW_PASSED'::character varying, 'INTERVIEW_FAILED'::character varying, 'FINAL_ACCEPTED'::character varying, 'FINAL_REJECTED'::character varying, 'WITHDRAWN'::character varying])::text[])),
    recruitment_id      bigint                      not null
        constraint fkp6pay5d5qymslgxs3d7ukepib
            references recruitment
);


create table evaluation
(
    id                bigint generated by default as identity
        primary key,
    decision          varchar(255) not null
        constraint evaluation_decision_check
            check ((decision)::text = ANY
        ((ARRAY ['PASS'::character varying, 'FAIL'::character varying, 'HOLD'::character varying])::text[])),
    evaluator_user_id bigint       not null,
    memo              varchar(255),
    score             integer,
    stage             varchar(255) not null
        constraint evaluation_stage_check
            check ((stage)::text = ANY
                   ((ARRAY ['DOCUMENT'::character varying, 'INTERVIEW'::character varying, 'FINAL'::character varying])::text[])),
    application_id    bigint       not null
        constraint fk8kmneeb146rbmsvm1jkhoy1s9
            references application
);

create table interview_slot
(
    id             bigint generated by default as identity
        primary key,
    ends_at        timestamp(6) with time zone not null,
    starts_at      timestamp(6) with time zone not null,
    recruitment_id bigint                      not null
        constraint fk5d4rto78f6rcvxf5ptgi255ir
            references recruitment
);

create table interview_assignment
(
    id             bigint generated by default as identity
        primary key,
    status         varchar(255) not null
        constraint interview_assignment_status_check
            check ((status)::text = ANY ((ARRAY ['DRAFT'::character varying, 'CONFIRMED'::character varying])::text[])),
    application_id bigint       not null
        constraint ukgenivp911m0qob6n8x7do8gt5
            unique
        constraint fkbiuwjuthpeeytmd7tqp8egi3v
            references application,
    recruitment_id bigint       not null
        constraint fkn9iegbrvvq8q6dcwr0l0ljpj8
            references recruitment,
    slot_id        bigint       not null
        constraint fkghgtyrf4074eti8dtlcnv6hra
            references interview_slot
);


create table recruitment_part
(
    id             bigint generated by default as identity
        primary key,
    part           varchar(255) not null
        constraint recruitment_part_part_check
            check ((part)::text = ANY
        ((ARRAY ['PLAN'::character varying, 'DESIGN'::character varying, 'WEB'::character varying, 'IOS'::character varying, 'ANDROID'::character varying, 'SPRINGBOOT'::character varying, 'NODEJS'::character varying])::text[])),
    recruitment_id bigint       not null,
    status         varchar(255) not null
        constraint recruitment_part_status_check
            check ((status)::text = ANY ((ARRAY ['OPEN'::character varying, 'CLOSED'::character varying])::text[]))
);


create table application_part_preference
(
    id                  bigint generated by default as identity
        primary key,
    priority            integer not null,
    application_id      bigint  not null
        constraint fkmrpw0lo117yicx1wvrdto4c0y
            references application,
    recruitment_part_id bigint  not null
        constraint fk3hamnhjhnk6c4357rtd4snl3w
            references recruitment_part
);


create table recruitment_schedule
(
    id             bigint generated by default as identity
        primary key,
    ends_at        timestamp(6) with time zone,
    note           varchar(255),
    recruitment_id bigint       not null,
    starts_at      timestamp(6) with time zone,
    type           varchar(255) not null
        constraint recruitment_schedule_type_check
            check ((type)::text = ANY
        ((ARRAY ['APPLY_WINDOW'::character varying, 'DOC_REVIEW_WINDOW'::character varying, 'DOC_RESULT_AT'::character varying, 'INTERVIEW_WINDOW'::character varying, 'FINAL_REVIEW_WINDOW'::character varying, 'FINAL_RESULT_AT'::character varying, 'OT_AT'::character varying, 'ACTIVITY_WINDOW'::character varying])::text[]))
    );


create table schedule_tags
(
    schedule_id bigint not null,
    tag         varchar(255)
        constraint schedule_tags_tag_check
            check ((tag)::text = ANY
        ((ARRAY ['LEADERSHIP'::character varying, 'STUDY'::character varying, 'DUES'::character varying, 'MEETING'::character varying, 'NETWORKING'::character varying, 'HACKATHON'::character varying, 'PROJECT'::character varying, 'PRESENTATION'::character varying, 'WORKSHOP'::character varying, 'RETROSPECTIVE'::character varying, 'AFTER_PARTY'::character varying, 'ORIENTATION'::character varying, 'GENERAL'::character varying])::text[]))
    );

create table school
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone not null,
    instagram_link varchar(255),
    kakao_link     varchar(255),
    logo_image_url varchar(255),
    name           varchar(255)                not null,
    remark         varchar(255),
    youtube_link   varchar(255)
);


create table chapter_school
(
    id         bigint generated by default as identity
        primary key,
    chapter_id bigint
        constraint fkkjdylii7vlq5n2a5tapt2p9an
            references chapter,
    school_id  bigint
        constraint fkmrnimigsrr31m9dxs8tjqip4
            references school
);

create table single_answer
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) with time zone not null,
    updated_at       timestamp(6) with time zone not null,
    answered_as_type varchar(255)                not null
        constraint single_answer_answered_as_type_check
            check ((answered_as_type)::text = ANY
        ((ARRAY ['SHORT_TEXT'::character varying, 'LONG_TEXT'::character varying, 'RADIO'::character varying, 'CHECKBOX'::character varying, 'DROPDOWN'::character varying, 'SCHEDULE'::character varying, 'PORTFOLIO'::character varying, 'PREFERRED_PART'::character varying])::text[])),
    value            jsonb                       not null,
    response_id      bigint                      not null
        constraint fkki99x99hyoalet42fu2ro4lic
            references form_response,
    question_id      bigint                      not null
        constraint fkpebjm0gybir74o50037lhvmsu
            references question
);


create table study_group
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    name       varchar(255),
    part       varchar(255)                not null
        constraint study_group_part_check
            check ((part)::text = ANY
        ((ARRAY ['PLAN'::character varying, 'DESIGN'::character varying, 'WEB'::character varying, 'IOS'::character varying, 'ANDROID'::character varying, 'SPRINGBOOT'::character varying, 'NODEJS'::character varying])::text[])),
    gisu_id    bigint
        constraint fkf0d4m9b1yjhn4tgggk4ceyjmo
            references gisu
);

create table study_group_member
(
    id            bigint generated by default as identity
        primary key,
    challenger_id bigint  not null,
    is_leader     boolean not null,
    group_id      bigint
        constraint fkok74qotmd7xqy9wvews3xv8iu
            references study_group
);

create table terms
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone not null,
    active         boolean                     not null,
    content        text                        not null,
    effective_date timestamp(6) with time zone not null,
    required       boolean                     not null,
    title          varchar(255)                not null,
    type           varchar(255)                not null
        constraint terms_type_check
            check ((type)::text = ANY
        ((ARRAY ['SERVICE'::character varying, 'PRIVACY'::character varying, 'MARKETING'::character varying, 'LOCATION'::character varying])::text[])),
    version        varchar(255)                not null
);


create table terms_consent
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    agreed_at  timestamp(6) with time zone not null,
    member_id  bigint                      not null,
    term_type  varchar(20)                 not null
        constraint terms_consent_term_type_check
            check ((term_type)::text = ANY
        ((ARRAY ['SERVICE'::character varying, 'PRIVACY'::character varying, 'MARKETING'::character varying, 'LOCATION'::character varying])::text[]))
    );

create table terms_consent_log
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    member_id   bigint                      not null,
    occurred_at timestamp(6) with time zone not null,
    status      varchar(20)                 not null
        constraint terms_consent_log_status_check
            check ((status)::text = ANY
        ((ARRAY ['AGREED'::character varying, 'WITHDRAWN'::character varying])::text[])),
    term_type   varchar(20)                 not null
        constraint terms_consent_log_term_type_check
            check ((term_type)::text = ANY
                   ((ARRAY ['SERVICE'::character varying, 'PRIVACY'::character varying, 'MARKETING'::character varying, 'LOCATION'::character varying])::text[]))
);


create table trophy
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    challenger_id bigint                      not null,
    content       text                        not null,
    title         varchar(255)                not null,
    url           varchar(255)                not null,
    week          integer                     not null
);


create table workbook_mission
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone not null,
    content              text,
    mission_type         varchar(255)                not null
        constraint workbook_mission_mission_type_check
            check ((mission_type)::text = ANY
        ((ARRAY ['LINK'::character varying, 'MEMO'::character varying, 'PLAIN'::character varying])::text[])),
    original_workbook_id bigint                      not null,
    title                varchar(255)                not null
);
