CREATE TABLE tech_blog_content
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(20)                  NOT NULL,
    slug         VARCHAR(200)                 NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE  NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE  NOT NULL,
    CONSTRAINT uk_tech_blog_content_type_slug UNIQUE (content_type, slug),
    CONSTRAINT tech_blog_content_type_check CHECK (content_type IN ('BLOG', 'RELEASE'))
);

CREATE TABLE tech_blog_content_like
(
    content_id BIGINT NOT NULL,
    member_id  BIGINT NOT NULL,
    CONSTRAINT pk_tech_blog_content_like PRIMARY KEY (content_id, member_id),
    CONSTRAINT fk_tech_blog_content_like_content
        FOREIGN KEY (content_id) REFERENCES tech_blog_content (id) ON DELETE CASCADE
);

CREATE TABLE tech_blog_comment
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id           BIGINT                     NOT NULL,
    parent_comment_id    BIGINT,
    author_member_id     BIGINT,
    anonymous            BOOLEAN                    NOT NULL,
    guest_nickname       VARCHAR(20),
    content              TEXT                       NOT NULL,
    deletion_type        VARCHAR(30)                NOT NULL DEFAULT 'NONE',
    deleted_at           TIMESTAMP(6) WITH TIME ZONE,
    deleted_by_member_id BIGINT,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tech_blog_comment_content
        FOREIGN KEY (content_id) REFERENCES tech_blog_content (id) ON DELETE CASCADE,
    CONSTRAINT fk_tech_blog_comment_parent
        FOREIGN KEY (parent_comment_id) REFERENCES tech_blog_comment (id) ON DELETE CASCADE,
    CONSTRAINT tech_blog_comment_deletion_type_check
        CHECK (deletion_type IN ('NONE', 'USER_DELETED', 'ADMIN_DELETED'))
);

CREATE TABLE tech_blog_comment_like
(
    comment_id BIGINT NOT NULL,
    member_id  BIGINT NOT NULL,
    CONSTRAINT pk_tech_blog_comment_like PRIMARY KEY (comment_id, member_id),
    CONSTRAINT fk_tech_blog_comment_like_comment
        FOREIGN KEY (comment_id) REFERENCES tech_blog_comment (id) ON DELETE CASCADE
);

CREATE INDEX idx_tech_blog_comment_content_parent_created
    ON tech_blog_comment (content_id, parent_comment_id, created_at, id);

CREATE INDEX idx_tech_blog_comment_parent_deletion
    ON tech_blog_comment (parent_comment_id, deletion_type);

CREATE INDEX idx_tech_blog_comment_like_comment
    ON tech_blog_comment_like (comment_id);
