CREATE TABLE inquiry
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    title                VARCHAR(255)                            NOT NULL,
    content              TEXT                                    NOT NULL,
    category             VARCHAR(30)                             NOT NULL,
    target               VARCHAR(20)                             NOT NULL,
    status               VARCHAR(20)                             NOT NULL DEFAULT 'RECEIVED',
    author_challenger_id BIGINT                                  NOT NULL,
    is_read              BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_inquiry PRIMARY KEY (id)
);

CREATE TABLE inquiry_message
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE                NOT NULL,
    inquiry_id           BIGINT                                  NOT NULL,
    sender_type          VARCHAR(20)                             NOT NULL,
    sender_challenger_id BIGINT                                  NOT NULL,
    content              TEXT                                    NOT NULL,
    CONSTRAINT pk_inquiry_message PRIMARY KEY (id)
);

CREATE TABLE inquiry_attachment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    inquiry_id       BIGINT                                  NOT NULL,
    file_metadata_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_inquiry_attachment PRIMARY KEY (id)
);

CREATE TABLE inquiry_message_attachment
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    inquiry_message_id BIGINT                                  NOT NULL,
    file_metadata_id   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_inquiry_message_attachment PRIMARY KEY (id)
);

ALTER TABLE inquiry_message
    ADD CONSTRAINT FK_INQUIRY_MESSAGE_ON_INQUIRY FOREIGN KEY (inquiry_id) REFERENCES inquiry (id);

ALTER TABLE inquiry_attachment
    ADD CONSTRAINT FK_INQUIRY_ATTACHMENT_ON_INQUIRY FOREIGN KEY (inquiry_id) REFERENCES inquiry (id);

ALTER TABLE inquiry_attachment
    ADD CONSTRAINT FK_INQUIRY_ATTACHMENT_ON_FILE_METADATA FOREIGN KEY (file_metadata_id) REFERENCES file_metadata (id);

ALTER TABLE inquiry_message_attachment
    ADD CONSTRAINT FK_INQUIRY_MESSAGE_ATTACHMENT_ON_INQUIRY_MESSAGE FOREIGN KEY (inquiry_message_id) REFERENCES inquiry_message (id);

ALTER TABLE inquiry_message_attachment
    ADD CONSTRAINT FK_INQUIRY_MESSAGE_ATTACHMENT_ON_FILE_METADATA FOREIGN KEY (file_metadata_id) REFERENCES file_metadata (id);

