CREATE TABLE public.event_outbox
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        uuid                        NOT NULL,
    event_type      varchar(150)                NOT NULL,
    payload         jsonb                       NOT NULL,
    status          varchar(20)                 NOT NULL DEFAULT 'PENDING',
    attempts        int                         NOT NULL DEFAULT 0,
    next_attempt_at timestamp(6) with time zone NOT NULL,
    last_error      text,
    created_at      timestamp(6) with time zone NOT NULL,
    updated_at      timestamp(6) with time zone NOT NULL,
    published_at    timestamp(6) with time zone
);

CREATE UNIQUE INDEX uq_event_outbox_event_id ON public.event_outbox (event_id);
CREATE INDEX idx_event_outbox_pending ON public.event_outbox (status, next_attempt_at, id);
