CREATE TABLE mission_feedback
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    mission_submission_id BIGINT                                  NOT NULL,
    reviewer_member_id    BIGINT                                  NOT NULL,
    content               TEXT                                    NOT NULL,
    feedback_result       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_mission_feedback PRIMARY KEY (id)
);

CREATE TABLE mission_submission
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    original_workbook_mission_id BIGINT                                  NOT NULL,
    challenger_workbook_id       BIGINT                                  NOT NULL,
    content                      TEXT,
    submitted_mission_as_type    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_mission_submission PRIMARY KEY (id)
);

CREATE TABLE weekly_best_workbook
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    member_id            BIGINT                                  NOT NULL,
    study_group_id       BIGINT,
    weekly_curriculum_id BIGINT                                  NOT NULL,
    best_reason          TEXT                                    NOT NULL,
    decided_member_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_weekly_best_workbook PRIMARY KEY (id)
);

ALTER TABLE weekly_best_workbook
    ADD CONSTRAINT uk_weekly_best_workbook_member_week_study_group UNIQUE (member_id, study_group_id, weekly_curriculum_id);

ALTER TABLE weekly_best_workbook
    ADD CONSTRAINT FK_WEEKLY_BEST_WORKBOOK_ON_WEEKLY_CURRICULUM FOREIGN KEY (weekly_curriculum_id) REFERENCES weekly_curriculum (id);

ALTER TABLE mission_feedback
    ADD CONSTRAINT FK_MISSION_FEEDBACK_ON_MISSION_SUBMISSION FOREIGN KEY (mission_submission_id) REFERENCES mission_submission (id);

ALTER TABLE mission_submission
    ADD CONSTRAINT FK_MISSION_SUBMISSION_ON_CHALLENGER_WORKBOOK FOREIGN KEY (challenger_workbook_id) REFERENCES challenger_workbook (id);

ALTER TABLE mission_submission
    ADD CONSTRAINT FK_MISSION_SUBMISSION_ON_ORIGINAL_WORKBOOK_MISSION FOREIGN KEY (original_workbook_mission_id) REFERENCES original_workbook_mission (id);

ALTER TABLE mission_submission
    ADD CONSTRAINT uk_mission_submission_original_wb_mission_challenger_wb_id UNIQUE (original_workbook_mission_id, challenger_workbook_id);

ALTER TABLE workbook_mission
    RENAME TO legacy_workbook_mission;

ALTER TABLE challenger_mission
    RENAME TO legacy_challenger_mission;
