CREATE TABLE project
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    gisu_id                     BIGINT                                  NOT NULL,
    chapter_id                  BIGINT                                  NOT NULL,
    status                      VARCHAR(255)                            NOT NULL,
    name                        VARCHAR(100)                            NOT NULL,
    description                 VARCHAR(200),
    logo_file_id                BIGINT,
    thumbnail_file_id           BIGINT,
    external_link               VARCHAR(300),
    product_owner_member_id     BIGINT                                  NOT NULL,
    status_changed_by_member_id BIGINT,
    status_changed_reason       VARCHAR(255),
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE project_application
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    project_application_form_id BIGINT                                  NOT NULL,
    form_response_id            BIGINT                                  NOT NULL,
    applicant_member_id         BIGINT                                  NOT NULL,
    applied_matching_round_id   BIGINT                                  NOT NULL,
    status                      VARCHAR(255)                            NOT NULL,
    status_changed_member_id    BIGINT,
    status_change_reason        VARCHAR(255),
    CONSTRAINT pk_project_application PRIMARY KEY (id)
);

CREATE TABLE project_application_form
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    project_id BIGINT                                  NOT NULL,
    form_id    BIGINT                   NOT NULL,
    CONSTRAINT pk_project_application_form PRIMARY KEY (id)
);

CREATE TABLE project_application_form_policy
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    project_application_form_id BIGINT                                  NOT NULL,
    form_section_id BIGINT                   NOT NULL,
    allowed_parts   TEXT[]                                  NOT NULL,
    CONSTRAINT pk_project_application_form_policy PRIMARY KEY (id)
);

CREATE TABLE project_matching_round
(
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL,
    name                      VARCHAR(255)             NOT NULL,
    description                      VARCHAR(255),
    type                      VARCHAR(255)             NOT NULL,
    phase                     VARCHAR(255)             NOT NULL,
    chapter_id                BIGINT                   NOT NULL,
    starts_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    decision_deadline         TIMESTAMP WITH TIME ZONE NOT NULL,
    auto_decision_executed_at TIMESTAMP WITH TIME ZONE,
    auto_decision_executed_member_id BIGINT,
    CONSTRAINT pk_project_matching_round PRIMARY KEY (id)
);

CREATE TABLE project_member
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    project_application_id   BIGINT,
    project_id               BIGINT                                  NOT NULL,
    member_id         BIGINT                   NOT NULL,
    is_leader                BOOLEAN                                 NOT NULL,
    description              VARCHAR(255),
    decided_member_id        BIGINT,
    decided_at        TIMESTAMP WITH TIME ZONE,
    status                   VARCHAR(255)                            NOT NULL,
    status_updated_at TIMESTAMP WITH TIME ZONE,
    status_change_reason     VARCHAR(255),
    status_changed_member_id BIGINT,
    CONSTRAINT pk_project_member PRIMARY KEY (id)
);

CREATE TABLE project_part_quota
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    project_id            BIGINT                                  NOT NULL,
    part                  VARCHAR(255)                            NOT NULL,
    quota                 BIGINT                                  NOT NULL,
    last_edited_member_id BIGINT,
    CONSTRAINT pk_project_part_quota PRIMARY KEY (id)
);

ALTER TABLE project_application
    ADD CONSTRAINT uk_project_application_form_member_matching_round UNIQUE (project_application_form_id,
                                                                             applied_matching_round_id,
                                                                             applicant_member_id);

ALTER TABLE project_matching_round
    ADD CONSTRAINT uk_project_matching_round_type_phase_chapter UNIQUE (type, phase, chapter_id);

ALTER TABLE project_member
    ADD CONSTRAINT uk_project_member_project_member UNIQUE (project_id, member_id);

ALTER TABLE project_part_quota
    ADD CONSTRAINT uk_project_part_quota_project_part UNIQUE (project_id, part);

ALTER TABLE project_application_form
    ADD CONSTRAINT FK_PROJECT_APPLICATION_FORM_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_application_form_policy
    ADD CONSTRAINT FK_PROJECT_APPLICATION_FORM_POLICY_ON_PROJECT_APPLICATION_FORM FOREIGN KEY (project_application_form_id) REFERENCES project_application_form (id);

ALTER TABLE project_application
    ADD CONSTRAINT FK_PROJECT_APPLICATION_ON_APPLIED_MATCHING_ROUND FOREIGN KEY (applied_matching_round_id) REFERENCES project_matching_round (id);

ALTER TABLE project_application
    ADD CONSTRAINT FK_PROJECT_APPLICATION_ON_PROJECT_APPLICATION_FORM FOREIGN KEY (project_application_form_id) REFERENCES project_application_form (id);

ALTER TABLE project_member
    ADD CONSTRAINT FK_PROJECT_MEMBER_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);

ALTER TABLE project_member
    ADD CONSTRAINT FK_PROJECT_MEMBER_ON_PROJECT_APPLICATION FOREIGN KEY (project_application_id) REFERENCES project_application (id);

ALTER TABLE project_part_quota
    ADD CONSTRAINT FK_PROJECT_PART_QUOTA_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);
