-- 1. study_group: gisu_id NOT NULL 설정
ALTER TABLE public.study_group ALTER COLUMN gisu_id SET NOT NULL;

-- 2. study_group_organizer 테이블 생성
CREATE TABLE public.study_group_organizer
(
    id             bigint                      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    study_group_id bigint                      NOT NULL,
    member_id      bigint                      NOT NULL,
    created_at     timestamp(6) with time zone NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL,
    CONSTRAINT study_group_organizer_pkey PRIMARY KEY (id),
    CONSTRAINT fk_study_group_organizer_study_group_id
        FOREIGN KEY (study_group_id) REFERENCES public.study_group (id)
);

-- 3. is_leader=true인 멤버를 organizer로 이관 (challenger_id → member_id 변환)
INSERT INTO public.study_group_organizer (study_group_id, member_id, created_at, updated_at)
SELECT sgm.group_id, c.member_id, sgm.created_at, sgm.updated_at
FROM public.study_group_member sgm
         JOIN public.challenger c ON c.id = sgm.challenger_id
WHERE sgm.is_leader = true;

-- 4. challenger_id → member_id 컬럼 교체
ALTER TABLE public.study_group_member ADD COLUMN member_id bigint;

UPDATE public.study_group_member sgm
SET member_id = c.member_id
FROM public.challenger c
WHERE c.id = sgm.challenger_id;

ALTER TABLE public.study_group_member ALTER COLUMN member_id SET NOT NULL;
ALTER TABLE public.study_group_member DROP COLUMN challenger_id;

-- 5. 전체 is_leader를 false로 초기화
UPDATE public.study_group_member SET is_leader = false;
