CREATE TABLE fcm_token_topic
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fcm_token_id BIGINT       NOT NULL,
    topic_name   VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_fcm_token_topic_fcm_token FOREIGN KEY (fcm_token_id) REFERENCES fcm_token (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uix_fcm_token_topic ON fcm_token_topic (fcm_token_id, topic_name);
CREATE INDEX ix_fcm_token_topic_fcm_token_id ON fcm_token_topic (fcm_token_id);
