-- LLM 분류 결과(domain_key) 를 키로 라우팅하는 신규 테이블.
-- 기존 figma_part_route 는 commit 5 의 마이그레이션에서 제거된다.
-- 1) figma_routing_domain : 도메인 단위 (어디로 보낼지)
-- 2) figma_routing_domain_mention : 도메인의 mention 대상 N개 (누구를 멘션할지)

CREATE TABLE figma_routing_domain
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_key           VARCHAR(100)                NOT NULL,
    description          VARCHAR(500),
    discord_webhook_url  TEXT                        NOT NULL,
    fallback             BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uix_figma_routing_domain_key ON figma_routing_domain (domain_key);
CREATE INDEX ix_figma_routing_domain_fallback ON figma_routing_domain (fallback);

CREATE TABLE figma_routing_domain_mention
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id       BIGINT                      NOT NULL,
    mention_id      VARCHAR(50)                 NOT NULL,
    mention_type    VARCHAR(20)                 NOT NULL,
    display_label   VARCHAR(255),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_frdm_domain FOREIGN KEY (domain_id) REFERENCES figma_routing_domain (id) ON DELETE CASCADE
);

CREATE INDEX ix_figma_routing_domain_mention_domain_id ON figma_routing_domain_mention (domain_id);
CREATE UNIQUE INDEX uix_figma_routing_domain_mention ON figma_routing_domain_mention (domain_id, mention_type, mention_id);
