CREATE TABLE chat_message
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE                NOT NULL,
    room_id           BIGINT                                  NOT NULL,
    sender_member_id  BIGINT,
    content_type      VARCHAR(20)                             NOT NULL,
    content           TEXT,
    file_metadata_ids TEXT[]                                  NOT NULL DEFAULT '{}',
    CONSTRAINT pk_chat_message PRIMARY KEY (id)
);

ALTER TABLE chat_message
    ADD CONSTRAINT fk_chat_message_room FOREIGN KEY (room_id) REFERENCES chat_room (id) ON DELETE CASCADE;


-- 읽음 처리 / 안 읽은 수 계산 기준
ALTER TABLE chat_member
    ADD COLUMN last_read_message_id BIGINT;
