CREATE TABLE user_feedback_template
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    context     VARCHAR(50)                 NOT NULL,
    target_type VARCHAR(50)                 NOT NULL,
    form_id     BIGINT                      NOT NULL,
    is_active   BOOLEAN                     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT user_feedback_template_context_check CHECK (context IN (
        'APPLICATION_SUBMITTED',
        'MATCHING_COMPLETED',
        'APPLICATION_MONITORING'
    )),
    CONSTRAINT user_feedback_template_target_type_check CHECK (target_type IN (
        'NEW_CHALLENGER',
        'EXPERIENCED_CHALLENGER',
        'ADMIN'
    ))
);

CREATE UNIQUE INDEX uq_user_feedback_template_active
    ON user_feedback_template (context, target_type)
    WHERE (is_active = TRUE);
