CREATE TABLE sso_authorization_code
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash             VARCHAR(64)  NOT NULL,
    member_id             BIGINT       NOT NULL,
    client_id             VARCHAR(100) NOT NULL,
    redirect_uri          VARCHAR(500) NOT NULL,
    code_challenge        VARCHAR(128) NOT NULL,
    code_challenge_method VARCHAR(20)  NOT NULL,
    expires_at            TIMESTAMPTZ  NOT NULL,
    used_at               TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_sso_authorization_code_hash UNIQUE (code_hash),
    CONSTRAINT ck_sso_authorization_code_challenge_method CHECK (code_challenge_method IN ('S256'))
);

CREATE INDEX ix_sso_authorization_code_expires_at
    ON sso_authorization_code (expires_at);

CREATE INDEX ix_sso_authorization_code_client_member
    ON sso_authorization_code (client_id, member_id);
