-- ADR-003: Figma 댓글 → Discord 포워딩 도메인 신설
-- 1) Figma OAuth 통합 상태 (운영진 1인 위임)
-- 2) 폴링 대상 파일과 sync 상태
-- 3) 페이지/프레임 이름 → 파트 role 매핑

CREATE TABLE figma_integration
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_member_id          BIGINT                      NOT NULL,
    refresh_token_enc        TEXT                        NOT NULL,
    access_token_enc         TEXT,
    access_token_expires_at  TIMESTAMP(6) WITH TIME ZONE,
    scope                    VARCHAR(500)                NOT NULL,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uix_figma_integration_owner ON figma_integration (owner_member_id);

CREATE TABLE figma_watched_file
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_key                 VARCHAR(100)                NOT NULL,
    display_name             VARCHAR(255)                NOT NULL,
    enabled                  BOOLEAN                     NOT NULL DEFAULT TRUE,
    last_synced_comment_id   VARCHAR(100),
    last_synced_at           TIMESTAMP(6) WITH TIME ZONE,
    last_error               TEXT,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uix_figma_watched_file_key ON figma_watched_file (file_key);
CREATE INDEX ix_figma_watched_file_enabled ON figma_watched_file (enabled);

CREATE TABLE figma_part_route
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_key                 VARCHAR(100)                NOT NULL,
    page_name                VARCHAR(255)                NOT NULL,
    part_key                 VARCHAR(50)                 NOT NULL,
    discord_role_id          VARCHAR(50)                 NOT NULL,
    discord_webhook_url      TEXT                        NOT NULL,
    fallback                 BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uix_figma_part_route_file_page ON figma_part_route (file_key, page_name);
CREATE INDEX ix_figma_part_route_file_key ON figma_part_route (file_key);
