CREATE TABLE weekly_challenger_workbook
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    weekly_curriculum_id BIGINT                                  NOT NULL,
    member_id            BIGINT,
    CONSTRAINT pk_weekly_challenger_workbook PRIMARY KEY (id)
);

ALTER TABLE weekly_challenger_workbook
    ADD CONSTRAINT FK_WEEKLY_CHALLENGER_WORKBOOK_ON_WEEKLY_CURRICULUM FOREIGN KEY (weekly_curriculum_id) REFERENCES weekly_curriculum (id);

-- 1. 기존 unique 제약 제거
ALTER TABLE challenger_workbook
DROP CONSTRAINT IF EXISTS uk_challenger_workbook_challenger_id_original_workbook_id;

-- 2. status CHECK 제약 제거
ALTER TABLE challenger_workbook
DROP CONSTRAINT IF EXISTS challenger_workbook_status_check;

-- 3. 제거 컬럼 DROP
ALTER TABLE challenger_workbook
DROP COLUMN IF EXISTS challenger_id,
    DROP COLUMN IF EXISTS schedule_id,
    DROP COLUMN IF EXISTS status,
    DROP COLUMN IF EXISTS best_reason,
    DROP COLUMN IF EXISTS feedback,
    DROP COLUMN IF EXISTS submission;

-- 4. 신규 컬럼 추가
ALTER TABLE challenger_workbook
    ADD COLUMN weekly_challenger_workbook_id bigint,
    ADD COLUMN content                       text,         -- nullable
    ADD COLUMN is_excused                    boolean,
    ADD COLUMN excused_reason                text,
    ADD COLUMN excuse_approved_member_id     bigint;

-- 5. 기존 row 기본값 채우기
UPDATE challenger_workbook
SET is_excused = false;

-- 6. NOT NULL 설정
ALTER TABLE challenger_workbook
    ALTER COLUMN is_excused SET NOT NULL;

-- 7. FK 제약 추가
ALTER TABLE challenger_workbook
    ADD CONSTRAINT fk_challenger_workbook_weekly_challenger_workbook_id
        FOREIGN KEY (weekly_challenger_workbook_id)
            REFERENCES weekly_challenger_workbook (id);
