-- 1. 기존 FK 제약 제거
ALTER TABLE original_workbook
DROP CONSTRAINT IF EXISTS fk_org_workbook_curr_id;

-- 2. mission_type CHECK 제약 제거
ALTER TABLE original_workbook
DROP CONSTRAINT IF EXISTS original_workbook_mission_type_check;

-- 3. 기존 컬럼 제거
ALTER TABLE original_workbook
DROP COLUMN IF EXISTS week_no,
    DROP COLUMN IF EXISTS curriculum_id,
    DROP COLUMN IF EXISTS start_date,
    DROP COLUMN IF EXISTS end_date,
    DROP COLUMN IF EXISTS mission_type,
    DROP COLUMN IF EXISTS workbook_url;

-- 4. 신규 컬럼 추가
ALTER TABLE original_workbook
    ADD COLUMN weekly_curriculum_id bigint,
    ADD COLUMN url                  varchar(255),
    ADD COLUMN original_workbook_status varchar(255),
    ADD COLUMN content              text,
    ADD COLUMN released_member_id   bigint,
    ADD COLUMN type                 varchar(255);

-- 5. 기존 데이터가 없다면 바로 NOT NULL 설정, 있다면 기본값 채운 후 설정
-- (데이터가 없는 경우 아래처럼 바로 NOT NULL 적용)
ALTER TABLE original_workbook
    ALTER COLUMN original_workbook_status SET NOT NULL,
    ALTER COLUMN type SET NOT NULL,
    ALTER COLUMN weekly_curriculum_id SET NOT NULL;

-- 6. 신규 FK 제약 추가 (weekly_curriculum 테이블이 존재해야 함)
ALTER TABLE original_workbook
    ADD CONSTRAINT fk_org_workbook_weekly_curriculum_id
        FOREIGN KEY (weekly_curriculum_id)
            REFERENCES weekly_curriculum (id);

CREATE TABLE original_workbook_mission
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    original_workbook_id BIGINT                                  NOT NULL,
    title                VARCHAR(255)                            NOT NULL,
    description          VARCHAR(255),
    mission_type         VARCHAR(255)                            NOT NULL,
    is_necessary         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_original_workbook_mission PRIMARY KEY (id)
);

CREATE TABLE weekly_curriculum
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    curriculum_id BIGINT,
    is_extra      BOOLEAN                                 NOT NULL,
    title         VARCHAR(255)                            NOT NULL,
    week_no       BIGINT                                  NOT NULL,
    starts_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ends_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_weekly_curriculum PRIMARY KEY (id)
);

ALTER TABLE original_workbook_mission
    ADD CONSTRAINT FK_ORIGINAL_WORKBOOK_MISSION_ON_ORIGINAL_WORKBOOK FOREIGN KEY (original_workbook_id) REFERENCES original_workbook (id);

ALTER TABLE weekly_curriculum
    ADD CONSTRAINT FK_WEEKLY_CURRICULUM_ON_CURRICULUM FOREIGN KEY (curriculum_id) REFERENCES curriculum (id);
