-- Figma 댓글 LLM 분류 결과의 영구 캐시.
-- in-memory Caffeine 캐시는 sync→preview 같은 짧은 시간 내 중복 호출 흡수용 (5분 TTL) 이고,
-- 본 테이블은 재시작/다중 인스턴스 환경에서도 동일 commentId 재호출을 방지하기 위한 영구 보관 계층이다.
-- mock provider 응답 / 후보 외 응답(domain_key=null) 은 영구 캐시하지 않고 in-memory 에만 둔다.

CREATE TABLE figma_comment_classification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id    VARCHAR(255)                NOT NULL,
    domain_key    VARCHAR(100)                NOT NULL,
    provider      VARCHAR(64)                 NOT NULL,
    classified_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uix_figma_comment_classification_comment_id
    ON figma_comment_classification (comment_id);
CREATE INDEX ix_figma_comment_classification_classified_at
    ON figma_comment_classification (classified_at);
