-- schedule_participant 테이블 생성

CREATE TABLE public.schedule_participant
(
    id                   bigint                      NOT NULL,
    member_id            bigint                      NOT NULL,
    schedule_id          bigint                      NOT NULL,
    location             public.geometry(Point, 4326),
    attendance_status    character varying(50),
    decided_by_member_id bigint,
    decided_at           timestamp(6) with time zone,
    decision_reason      varchar(300),
    is_location_verified boolean,
    excuse_reason        varchar(300),
    created_at           timestamp(6) with time zone NOT NULL,
    updated_at           timestamp(6) with time zone NOT NULL,
    CONSTRAINT schedule_participant_attendance_status_check CHECK (
        (attendance_status)::text = ANY (
            (ARRAY [
                'PRESENT':: character varying,
                'PRESENT_PENDING':: character varying,
                'LATE':: character varying,
                'LATE_PENDING':: character varying,
                'ABSENT':: character varying,
                'EXCUSED':: character varying,
                'EXCUSED_PENDING':: character varying,
                'LATE_EXCUSE_PENDING':: character varying,
                'ABSENT_EXCUSE_PENDING':: character varying
                ])::text[]
            )
        )
);

ALTER TABLE public.schedule_participant
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.schedule_participant_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );

ALTER TABLE ONLY public.schedule_participant
    ADD CONSTRAINT schedule_participant_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.schedule_participant
    ADD CONSTRAINT fk_schedule_participant_schedule
        FOREIGN KEY (schedule_id) REFERENCES public.schedule (id);
