CREATE TABLE blog_content
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type         VARCHAR(20)                  NOT NULL,
    slug                 VARCHAR(200)                 NOT NULL,
    title                VARCHAR(200)                 NOT NULL,
    summary              VARCHAR(500),
    thumbnail_url        VARCHAR(1000),
    content              TEXT                         NOT NULL,
    status               VARCHAR(20)                  NOT NULL,
    author_member_id     BIGINT                       NOT NULL,
    published_at         TIMESTAMP(6) WITH TIME ZONE,
    deleted_at           TIMESTAMP(6) WITH TIME ZONE,
    deleted_by_member_id BIGINT,
    seo_title            VARCHAR(200),
    seo_description      VARCHAR(500),
    og_image_url         VARCHAR(1000),
    created_at           TIMESTAMP(6) WITH TIME ZONE  NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE  NOT NULL,
    CONSTRAINT uk_blog_content_type_slug UNIQUE (content_type, slug),
    CONSTRAINT blog_content_type_check CHECK (content_type IN ('BLOG', 'RELEASE')),
    CONSTRAINT blog_content_status_check CHECK (status IN ('DRAFT', 'PUBLISHED', 'DELETED'))
);

CREATE INDEX idx_blog_content_public
    ON blog_content (status, content_type, published_at, id);

CREATE INDEX idx_blog_content_author
    ON blog_content (author_member_id);

CREATE TABLE blog_content_like
(
    content_id BIGINT                      NOT NULL,
    member_id  BIGINT                      NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_blog_content_like PRIMARY KEY (content_id, member_id),
    CONSTRAINT fk_blog_content_like_content
        FOREIGN KEY (content_id) REFERENCES blog_content (id) ON DELETE CASCADE
);

CREATE TABLE blog_comment
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id           BIGINT                      NOT NULL,
    parent_comment_id    BIGINT,
    author_member_id     BIGINT,
    anonymous            BOOLEAN                     NOT NULL,
    nickname             VARCHAR(20),
    content              TEXT                        NOT NULL,
    deletion_type        VARCHAR(30)                 NOT NULL DEFAULT 'NONE',
    deleted_at           TIMESTAMP(6) WITH TIME ZONE,
    deleted_by_member_id BIGINT,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_blog_comment_content
        FOREIGN KEY (content_id) REFERENCES blog_content (id) ON DELETE CASCADE,
    CONSTRAINT fk_blog_comment_parent
        FOREIGN KEY (parent_comment_id) REFERENCES blog_comment (id) ON DELETE CASCADE,
    CONSTRAINT blog_comment_deletion_type_check
        CHECK (deletion_type IN ('NONE', 'USER_DELETED', 'ADMIN_DELETED'))
);

CREATE TABLE blog_comment_like
(
    comment_id BIGINT                      NOT NULL,
    member_id  BIGINT                      NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_blog_comment_like PRIMARY KEY (comment_id, member_id),
    CONSTRAINT fk_blog_comment_like_comment
        FOREIGN KEY (comment_id) REFERENCES blog_comment (id) ON DELETE CASCADE
);

CREATE TABLE blog_series
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type         VARCHAR(20)                  NOT NULL,
    slug                 VARCHAR(200)                 NOT NULL,
    title                VARCHAR(200)                 NOT NULL,
    description          VARCHAR(1000),
    thumbnail_url        VARCHAR(1000),
    author_member_id     BIGINT                       NOT NULL,
    deleted_at           TIMESTAMP(6) WITH TIME ZONE,
    deleted_by_member_id BIGINT,
    seo_title            VARCHAR(200),
    seo_description      VARCHAR(500),
    og_image_url         VARCHAR(1000),
    created_at           TIMESTAMP(6) WITH TIME ZONE  NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE  NOT NULL,
    CONSTRAINT uk_blog_series_type_slug UNIQUE (content_type, slug),
    CONSTRAINT blog_series_type_check CHECK (content_type IN ('BLOG', 'RELEASE'))
);

CREATE TABLE blog_series_content
(
    series_id     BIGINT                      NOT NULL,
    content_id    BIGINT                      NOT NULL,
    display_order INTEGER                     NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_blog_series_content PRIMARY KEY (series_id, content_id),
    CONSTRAINT uk_blog_series_content_order UNIQUE (series_id, display_order),
    CONSTRAINT fk_blog_series_content_series
        FOREIGN KEY (series_id) REFERENCES blog_series (id) ON DELETE CASCADE,
    CONSTRAINT fk_blog_series_content_content
        FOREIGN KEY (content_id) REFERENCES blog_content (id) ON DELETE CASCADE
);

CREATE TABLE blog_hashtag
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(30)                 NOT NULL,
    normalized_name VARCHAR(30)                 NOT NULL,
    slug            VARCHAR(30)                 NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_blog_hashtag_normalized_name UNIQUE (normalized_name),
    CONSTRAINT uk_blog_hashtag_slug UNIQUE (slug)
);

CREATE TABLE blog_content_hashtag
(
    content_id    BIGINT                      NOT NULL,
    hashtag_id    BIGINT                      NOT NULL,
    display_order INTEGER                     NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_blog_content_hashtag PRIMARY KEY (content_id, hashtag_id),
    CONSTRAINT uk_blog_content_hashtag_order UNIQUE (content_id, display_order),
    CONSTRAINT fk_blog_content_hashtag_content
        FOREIGN KEY (content_id) REFERENCES blog_content (id) ON DELETE CASCADE,
    CONSTRAINT fk_blog_content_hashtag_hashtag
        FOREIGN KEY (hashtag_id) REFERENCES blog_hashtag (id) ON DELETE CASCADE
);

CREATE INDEX idx_blog_comment_content_parent_created
    ON blog_comment (content_id, parent_comment_id, created_at, id);

CREATE INDEX idx_blog_comment_parent_deletion
    ON blog_comment (parent_comment_id, deletion_type);

CREATE INDEX idx_blog_comment_like_comment
    ON blog_comment_like (comment_id);

CREATE INDEX idx_blog_series_content_series_order
    ON blog_series_content (series_id, display_order, content_id);

CREATE INDEX idx_blog_series_content_content
    ON blog_series_content (content_id);

CREATE INDEX idx_blog_content_hashtag_hashtag
    ON blog_content_hashtag (hashtag_id, content_id);
