CREATE TABLE maintenance_window (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    scope             VARCHAR(32)                             NOT NULL,
    target_domains    VARCHAR(512),
    start_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    title             VARCHAR(255)                            NOT NULL,
    message           VARCHAR(1000)                           NOT NULL,
    forced_ended_at   TIMESTAMP WITHOUT TIME ZONE,
    created_by        BIGINT                                  NOT NULL,
    CONSTRAINT pk_maintenance_window PRIMARY KEY (id)
);

CREATE INDEX idx_maintenance_window_active
    ON maintenance_window (start_at, end_at)
    WHERE forced_ended_at IS NULL;
