-- =====================================================================================
-- Figma 도메인 통합 마이그레이션
-- ADR-003 (Figma 댓글 → Discord 포워딩) + amendment 1·2차 (LLM 분류 + 도메인 라우팅 + embed)
-- ADR-004 (시간창 단일 유즈케이스 + 중복 발송 가드)
--
-- 본 파일은 figma 도메인의 모든 테이블을 한 번에 정의한다. 본래 figma 도메인은 V10.00 /
-- V10.10 / V10.20 / V21.30 4개 마이그레이션으로 점진 진화했으나, 4종 모두 develop/main 에
-- 미머지 상태였으므로 단일 파일로 병합했다 (ADR-004 §Decision 5). 이후 figma 도메인 스키마
-- 변경은 신규 V2026.MM.DD 파일을 추가하는 정상 패턴으로 진행한다.
-- =====================================================================================


-- ADR-003 §Decision 1: Figma OAuth refresh/access token 보관 (운영진 1인 위임)
CREATE TABLE figma_integration
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_member_id          BIGINT                      NOT NULL,
    refresh_token_enc        TEXT                        NOT NULL,
    access_token_enc         TEXT,
    access_token_expires_at  TIMESTAMP(6) WITH TIME ZONE,
    scope                    VARCHAR(500)                NOT NULL,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uix_figma_integration_owner ON figma_integration (owner_member_id);


-- ADR-003 §Decision 2: 폴링 대상 파일 메타데이터 (file_key, 활성 여부, 마지막 fetch 시각)
-- last_synced_comment_id 컬럼은 ADR-004 채택 직후 별도 커밋에서 제거된다.
-- (단일 커밋 안에서 컬럼을 정리하면 빌드가 깨지므로, 진입점 위임 완료 후 정리한다.)
CREATE TABLE figma_watched_file
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_key                 VARCHAR(100)                NOT NULL,
    display_name             VARCHAR(255)                NOT NULL,
    enabled                  BOOLEAN                     NOT NULL DEFAULT TRUE,
    last_synced_comment_id   VARCHAR(100),
    last_synced_at           TIMESTAMP(6) WITH TIME ZONE,
    last_error               TEXT,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uix_figma_watched_file_key      ON figma_watched_file (file_key);
CREATE INDEX        ix_figma_watched_file_enabled   ON figma_watched_file (enabled);


-- ADR-003 amendment 1차 (2026-05-07): 페이지명 매핑 대신 LLM 분류 결과(domain_key) 를
--   라우팅 키로 사용. 도메인 단위로 Discord webhook URL 1개를 묶고, 멘션 대상은 N개까지
--   영속화한다. 본 통합 시점에 폐기된 figma_part_route 는 정의하지 않는다.
CREATE TABLE figma_routing_domain
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_key           VARCHAR(100)                NOT NULL,
    description          VARCHAR(500),
    discord_webhook_url  TEXT                        NOT NULL,
    fallback             BOOLEAN                     NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uix_figma_routing_domain_key      ON figma_routing_domain (domain_key);
CREATE INDEX        ix_figma_routing_domain_fallback  ON figma_routing_domain (fallback);


-- ADR-003 amendment 1차: 도메인별 멘션 대상 (Discord role / user) N개. embed 외부 content 영역에 출력.
CREATE TABLE figma_routing_domain_mention
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id       BIGINT                      NOT NULL,
    mention_id      VARCHAR(50)                 NOT NULL,
    mention_type    VARCHAR(20)                 NOT NULL,
    display_label   VARCHAR(255),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_frdm_domain FOREIGN KEY (domain_id) REFERENCES figma_routing_domain (id) ON DELETE CASCADE
);

CREATE INDEX        ix_figma_routing_domain_mention_domain_id ON figma_routing_domain_mention (domain_id);
CREATE UNIQUE INDEX uix_figma_routing_domain_mention          ON figma_routing_domain_mention (domain_id, mention_type, mention_id);


-- ADR-003 amendment 후속 (3-tier 분류 캐시 §L2): commentId → domain_key 영구 캐시.
--   재시작/다중 인스턴스 환경에서도 동일 commentId 의 LLM 재호출을 막는다.
--   mock provider 응답 / 후보 외 응답은 본 테이블에 저장하지 않고 in-memory L1 캐시에만 둔다.
CREATE TABLE figma_comment_classification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id    VARCHAR(255)                NOT NULL,
    domain_key    VARCHAR(100)                NOT NULL,
    provider      VARCHAR(64)                 NOT NULL,
    classified_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uix_figma_comment_classification_comment_id   ON figma_comment_classification (comment_id);
CREATE INDEX        ix_figma_comment_classification_classified_at ON figma_comment_classification (classified_at);


-- ADR-004 §Decision 4: 단일 행 전역 cursor. 스케줄러는 (last_window_end, now] 시간창을 사용하며,
--   발송 성공 시 last_window_end 를 now 로 advance 한다. 다중 인스턴스 환경에서는 SELECT FOR UPDATE
--   또는 ShedLock 으로 직렬화한다. application 코드가 단일 row 불변을 보장한다.
CREATE TABLE figma_summary_cursor
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_window_end   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL
);


-- ADR-004 §Decision 3: 댓글 단위 발송 기록. 시간창 시맨틱으로 옮기면서 사라진
--   "이미 발송된 댓글을 다시 보내지 않는다" 가드 책임을 본 테이블이 담당한다.
--   admin digest 는 force=true 로 본 테이블을 무시하고 재발송할 수 있다 (catch-up 시맨틱 유지).
--   90일 보존이며 별도 회수 잡으로 정리한다 (ADR-004 §Implementation Plan §7).
CREATE TABLE figma_comment_dispatch
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id      VARCHAR(255)                NOT NULL,
    domain_id       BIGINT                      NOT NULL,
    dispatched_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_fcd_domain FOREIGN KEY (domain_id) REFERENCES figma_routing_domain (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uix_figma_comment_dispatch_comment_id   ON figma_comment_dispatch (comment_id);
CREATE INDEX        ix_figma_comment_dispatch_dispatched_at ON figma_comment_dispatch (dispatched_at);
