CREATE
EXTENSION IF NOT EXISTS postgis;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;

--
-- Name: application; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application
(
    doc_score           numeric(38, 2),
    final_score         numeric(38, 2),
    interview_score     numeric(38, 2),
    applicant_member_id bigint                      NOT NULL,
    created_at          timestamp(6) with time zone NOT NULL,
    form_response_id    bigint                      NOT NULL,
    id                  bigint                      NOT NULL,
    recruitment_id      bigint                      NOT NULL,
    updated_at          timestamp(6) with time zone NOT NULL,
    selected_part       character varying(255),
    status              character varying(255)      NOT NULL,
    CONSTRAINT application_selected_part_check CHECK (((selected_part)::text = ANY ((ARRAY['PLAN':: character varying, 'DESIGN':: character varying, 'WEB':: character varying, 'ANDROID':: character varying, 'IOS':: character varying, 'NODEJS':: character varying, 'SPRINGBOOT':: character varying])::text[])
) ),
    CONSTRAINT application_status_check CHECK (((status)::text = ANY ((ARRAY['APPLIED'::character varying, 'DOC_PASSED'::character varying, 'DOC_FAILED'::character varying, 'INTERVIEW_SCHEDULED'::character varying, 'INTERVIEW_PASSED'::character varying, 'INTERVIEW_FAILED'::character varying, 'FINAL_ACCEPTED'::character varying, 'FINAL_REJECTED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


--
-- Name: application_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_part_preference; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_part_preference
(
    priority            integer                     NOT NULL,
    application_id      bigint                      NOT NULL,
    created_at          timestamp(6) with time zone NOT NULL,
    id                  bigint                      NOT NULL,
    recruitment_part_id bigint                      NOT NULL,
    updated_at          timestamp(6) with time zone NOT NULL
);


--
-- Name: application_part_preference_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application_part_preference ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_part_preference_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_record
(
    latitude            double precision,
    location_verified   boolean                     NOT NULL,
    longitude           double precision,
    attendance_sheet_id bigint                      NOT NULL,
    checked_at          timestamp(6) with time zone,
    confirmed_at        timestamp(6) with time zone,
    confirmed_by        bigint,
    created_at          timestamp(6) with time zone NOT NULL,
    id                  bigint                      NOT NULL,
    member_id           bigint                      NOT NULL,
    updated_at          timestamp(6) with time zone NOT NULL,
    memo                character varying(500),
    status              character varying(255)      NOT NULL,
    CONSTRAINT attendance_record_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING':: character varying, 'PRESENT':: character varying, 'PRESENT_PENDING':: character varying, 'LATE':: character varying, 'LATE_PENDING':: character varying, 'ABSENT':: character varying, 'EXCUSED':: character varying, 'EXCUSED_PENDING':: character varying])::text[])
) )
);


--
-- Name: attendance_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_sheet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_sheet
(
    active                 boolean                     NOT NULL,
    late_threshold_minutes integer                     NOT NULL,
    requires_approval      boolean                     NOT NULL,
    created_at             timestamp(6) with time zone NOT NULL,
    end_time               timestamp(6) with time zone NOT NULL,
    gisu_id                bigint                      NOT NULL,
    id                     bigint                      NOT NULL,
    schedule_id            bigint                      NOT NULL,
    start_time             timestamp(6) with time zone NOT NULL,
    updated_at             timestamp(6) with time zone NOT NULL
);


--
-- Name: attendance_sheet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance_sheet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_sheet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: central_organization; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.central_organization
(
    created_at timestamp(6) with time zone NOT NULL,
    gisu_id    bigint,
    id         bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    name       character varying(255)
);


--
-- Name: central_organization_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.central_organization ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.central_organization_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenger; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenger
(
    created_at          timestamp(6) with time zone NOT NULL,
    gisu_id             bigint                      NOT NULL,
    id                  bigint                      NOT NULL,
    member_id           bigint                      NOT NULL,
    modified_by         bigint,
    updated_at          timestamp(6) with time zone NOT NULL,
    modification_reason character varying(255),
    part                character varying(255)      NOT NULL,
    status              character varying(255)      NOT NULL,
    CONSTRAINT challenger_part_check CHECK (((part)::text = ANY ((ARRAY['PLAN':: character varying, 'DESIGN':: character varying, 'WEB':: character varying, 'ANDROID':: character varying, 'IOS':: character varying, 'NODEJS':: character varying, 'SPRINGBOOT':: character varying])::text[])
) ),
    CONSTRAINT challenger_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'GRADUATED'::character varying, 'EXPELLED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


--
-- Name: challenger_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenger ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenger_mission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenger_mission
(
    challenger_workbook_id bigint                      NOT NULL,
    created_at             timestamp(6) with time zone NOT NULL,
    id                     bigint                      NOT NULL,
    updated_at             timestamp(6) with time zone NOT NULL,
    workbook_mission_id    bigint                      NOT NULL,
    submission             text
);


--
-- Name: challenger_mission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenger_mission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenger_mission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenger_point; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenger_point
(
    challenger_id bigint                      NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    id            bigint                      NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    description   character varying(200),
    point         character varying(255)      NOT NULL,
    CONSTRAINT challenger_point_point_check CHECK (((point)::text = ANY ((ARRAY['BEST_WORKBOOK':: character varying, 'WARNING':: character varying, 'OUT':: character varying])::text[])
) )
);


--
-- Name: challenger_point_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenger_point ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenger_point_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenger_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenger_record
(
    is_used           boolean                     NOT NULL,
    code              character varying(6)        NOT NULL,
    chapter_id        bigint                      NOT NULL,
    created_at        timestamp(6) with time zone NOT NULL,
    created_member_id bigint                      NOT NULL,
    gisu_id           bigint                      NOT NULL,
    id                bigint                      NOT NULL,
    school_id         bigint                      NOT NULL,
    updated_at        timestamp(6) with time zone NOT NULL,
    used_at           timestamp(6) with time zone,
    used_member_id    bigint,
    part              character varying(255)      NOT NULL,
    CONSTRAINT challenger_record_part_check CHECK (((part)::text = ANY ((ARRAY['PLAN':: character varying, 'DESIGN':: character varying, 'WEB':: character varying, 'ANDROID':: character varying, 'IOS':: character varying, 'NODEJS':: character varying, 'SPRINGBOOT':: character varying])::text[])
) )
);


--
-- Name: challenger_record_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenger_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenger_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenger_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenger_role
(
    challenger_id     bigint                      NOT NULL,
    created_at        timestamp(6) with time zone NOT NULL,
    gisu_id           bigint                      NOT NULL,
    id                bigint                      NOT NULL,
    organization_id   bigint,
    updated_at        timestamp(6) with time zone NOT NULL,
    organization_type character varying(255)      NOT NULL,
    responsible_part  character varying(255),
    role_type         character varying(255)      NOT NULL,
    CONSTRAINT challenger_role_organization_type_check CHECK (((organization_type)::text = ANY ((ARRAY['CENTRAL':: character varying, 'CHAPTER':: character varying, 'SCHOOL':: character varying])::text[])
) ),
    CONSTRAINT challenger_role_responsible_part_check CHECK (((responsible_part)::text = ANY ((ARRAY['PLAN'::character varying, 'DESIGN'::character varying, 'WEB'::character varying, 'ANDROID'::character varying, 'IOS'::character varying, 'NODEJS'::character varying, 'SPRINGBOOT'::character varying])::text[]))),
    CONSTRAINT challenger_role_role_type_check CHECK (((role_type)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'CENTRAL_PRESIDENT'::character varying, 'CENTRAL_VICE_PRESIDENT'::character varying, 'CENTRAL_OPERATING_TEAM_MEMBER'::character varying, 'CENTRAL_EDUCATION_TEAM_MEMBER'::character varying, 'CHAPTER_PRESIDENT'::character varying, 'SCHOOL_PRESIDENT'::character varying, 'SCHOOL_VICE_PRESIDENT'::character varying, 'SCHOOL_PART_LEADER'::character varying, 'SCHOOL_ETC_ADMIN'::character varying])::text[])))
);


--
-- Name: challenger_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenger_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenger_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenger_workbook; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenger_workbook
(
    challenger_id        bigint                      NOT NULL,
    created_at           timestamp(6) with time zone NOT NULL,
    id                   bigint                      NOT NULL,
    original_workbook_id bigint                      NOT NULL,
    schedule_id          bigint                      NOT NULL,
    updated_at           timestamp(6) with time zone NOT NULL,
    best_reason          text,
    feedback             text,
    status               character varying(255)      NOT NULL,
    submission           text,
    CONSTRAINT challenger_workbook_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING':: character varying, 'SUBMITTED':: character varying, 'PASS':: character varying, 'FAIL':: character varying, 'BEST':: character varying])::text[])
) )
);


--
-- Name: challenger_workbook_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenger_workbook ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenger_workbook_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chapter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chapter
(
    created_at timestamp(6) with time zone NOT NULL,
    gisu_id    bigint,
    id         bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    name       character varying(255)
);


--
-- Name: chapter_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chapter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chapter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chapter_school; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chapter_school
(
    chapter_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    id         bigint                      NOT NULL,
    school_id  bigint,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: chapter_school_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chapter_school ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chapter_school_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment
(
    challenger_id bigint                      NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    id            bigint                      NOT NULL,
    parent_id     bigint,
    post_id       bigint                      NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    content       text                        NOT NULL
);


--
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comment_like
(
    challenger_id bigint,
    comment_id    bigint NOT NULL
);


--
-- Name: curriculum; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.curriculum
(
    created_at timestamp(6) with time zone NOT NULL,
    gisu_id    bigint                      NOT NULL,
    id         bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    part       character varying(255)      NOT NULL,
    title      character varying(255)      NOT NULL,
    CONSTRAINT curriculum_part_check CHECK (((part)::text = ANY ((ARRAY['PLAN':: character varying, 'DESIGN':: character varying, 'WEB':: character varying, 'ANDROID':: character varying, 'IOS':: character varying, 'NODEJS':: character varying, 'SPRINGBOOT':: character varying])::text[])
) )
);


--
-- Name: curriculum_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.curriculum ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.curriculum_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_verification
(
    is_verified boolean                     NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL,
    expires_at  timestamp(6) with time zone NOT NULL,
    id          bigint                      NOT NULL,
    updated_at  timestamp(6) with time zone NOT NULL,
    verified_at timestamp(6) with time zone,
    code        character varying(10)       NOT NULL,
    verified_by character varying(30),
    token       character varying(100)      NOT NULL,
    email       character varying(200)      NOT NULL
);


--
-- Name: email_verification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_verification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.evaluation
(
    score             integer,
    application_id    bigint                      NOT NULL,
    created_at        timestamp(6) with time zone NOT NULL,
    evaluator_user_id bigint                      NOT NULL,
    id                bigint                      NOT NULL,
    updated_at        timestamp(6) with time zone NOT NULL,
    comments          character varying(255),
    stage             character varying(255)      NOT NULL,
    status            character varying(255)      NOT NULL,
    CONSTRAINT evaluation_stage_check CHECK (((stage)::text = ANY ((ARRAY['DOCUMENT':: character varying, 'INTERVIEW':: character varying, 'FINAL':: character varying])::text[])
) ),
    CONSTRAINT evaluation_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'SUBMITTED'::character varying])::text[])))
);


--
-- Name: evaluation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.evaluation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fcm_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fcm_token
(
    created_at timestamp(6) with time zone NOT NULL,
    id         bigint                      NOT NULL,
    member_id  bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    fcm_token  text
);


--
-- Name: fcm_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fcm_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fcm_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: file_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.file_metadata
(
    is_uploaded        boolean                     NOT NULL,
    created_at         timestamp(6) with time zone NOT NULL,
    file_size          bigint                      NOT NULL,
    updated_at         timestamp(6) with time zone NOT NULL,
    uploaded_member_id bigint,
    category           character varying(50)       NOT NULL,
    storage_provider   character varying(50)       NOT NULL,
    content_type       character varying(100)      NOT NULL,
    storage_key        character varying(500)      NOT NULL,
    id                 character varying(255)      NOT NULL,
    original_file_name character varying(255)      NOT NULL,
    CONSTRAINT file_metadata_category_check CHECK (((category)::text = ANY ((ARRAY['PROFILE_IMAGE':: character varying, 'POST_IMAGE':: character varying, 'POST_ATTACHMENT':: character varying, 'NOTICE_ATTACHMENT':: character varying, 'WORKBOOK_SUBMISSION':: character varying, 'SCHOOL_LOGO':: character varying, 'PORTFOLIO':: character varying, 'ETC':: character varying])::text[])
) ),
    CONSTRAINT file_metadata_storage_provider_check CHECK (((storage_provider)::text = ANY ((ARRAY['AWS_S3'::character varying, 'GOOGLE_CLOUD_STORAGE'::character varying])::text[])))
);


--
-- Name: form; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form
(
    is_anonymous      boolean                     NOT NULL,
    created_at        timestamp(6) with time zone NOT NULL,
    created_member_id bigint                      NOT NULL,
    ends_at_exclusive timestamp(6) with time zone,
    id                bigint                      NOT NULL,
    starts_at         timestamp(6) with time zone,
    updated_at        timestamp(6) with time zone NOT NULL,
    description       character varying(500),
    status            character varying(255)      NOT NULL,
    title             character varying(255),
    CONSTRAINT form_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT':: character varying, 'PUBLISHED':: character varying])::text[])
) )
);


--
-- Name: form_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.form ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: form_response; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_response
(
    created_at           timestamp(6) with time zone NOT NULL,
    form_id              bigint                      NOT NULL,
    id                   bigint                      NOT NULL,
    last_saved_at        timestamp(6) with time zone NOT NULL,
    respondent_member_id bigint                      NOT NULL,
    submitted_at         timestamp(6) with time zone,
    updated_at           timestamp(6) with time zone NOT NULL,
    status               character varying(255)      NOT NULL,
    submitted_ip         character varying(255),
    CONSTRAINT form_response_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT':: character varying, 'SUBMITTED':: character varying])::text[])
) )
);


--
-- Name: form_response_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.form_response ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.form_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: form_section; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.form_section
(
    order_no    integer,
    created_at  timestamp(6) with time zone NOT NULL,
    form_id     bigint                      NOT NULL,
    id          bigint                      NOT NULL,
    updated_at  timestamp(6) with time zone NOT NULL,
    target_key  character varying(50),
    description character varying(500),
    title       character varying(255)      NOT NULL,
    type        character varying(255)      NOT NULL,
    CONSTRAINT form_section_type_check CHECK (((type)::text = ANY ((ARRAY['DEFAULT':: character varying, 'CUSTOM':: character varying])::text[])
) )
);


--
-- Name: form_section_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.form_section ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.form_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gisu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gisu
(
    is_active  boolean,
    created_at timestamp(6) with time zone NOT NULL,
    end_at     timestamp(6) with time zone,
    generation bigint,
    id         bigint                      NOT NULL,
    start_at   timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: gisu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gisu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gisu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_assignment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_assignment
(
    application_id bigint                      NOT NULL,
    created_at     timestamp(6) with time zone NOT NULL,
    id             bigint                      NOT NULL,
    recruitment_id bigint                      NOT NULL,
    slot_id        bigint                      NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL
);


--
-- Name: interview_assignment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_assignment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_live_question; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_live_question
(
    application_id   bigint                      NOT NULL,
    author_member_id bigint                      NOT NULL,
    created_at       timestamp(6) with time zone NOT NULL,
    id               bigint                      NOT NULL,
    updated_at       timestamp(6) with time zone NOT NULL,
    content          character varying(300)      NOT NULL
);


--
-- Name: interview_live_question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_live_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_live_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_question_sheet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_question_sheet
(
    order_no       integer                     NOT NULL,
    created_at     timestamp(6) with time zone NOT NULL,
    id             bigint                      NOT NULL,
    recruitment_id bigint                      NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL,
    part_key       character varying(30)       NOT NULL,
    content        character varying(300)      NOT NULL,
    CONSTRAINT interview_question_sheet_part_key_check CHECK (((part_key)::text = ANY ((ARRAY['COMMON':: character varying, 'PLAN':: character varying, 'DESIGN':: character varying, 'WEB':: character varying, 'IOS':: character varying, 'ANDROID':: character varying, 'SPRINGBOOT':: character varying, 'NODEJS':: character varying])::text[])
) )
);


--
-- Name: interview_question_sheet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_question_sheet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_question_sheet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_slot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interview_slot
(
    created_at     timestamp(6) with time zone NOT NULL,
    ends_at        timestamp(6) with time zone NOT NULL,
    id             bigint                      NOT NULL,
    recruitment_id bigint                      NOT NULL,
    starts_at      timestamp(6) with time zone NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL
);


--
-- Name: interview_slot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_slot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_slot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member
(
    created_at       timestamp(6) with time zone NOT NULL,
    id               bigint                      NOT NULL,
    profile_id       bigint,
    school_id        bigint,
    updated_at       timestamp(6) with time zone NOT NULL,
    nickname         character varying(20)       NOT NULL,
    status           character varying(20)       NOT NULL,
    name             character varying(30)       NOT NULL,
    email            character varying(100)      NOT NULL,
    profile_image_id character varying(255),
    CONSTRAINT member_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE':: character varying, 'INACTIVE':: character varying, 'WITHDRAWN':: character varying])::text[])
) )
);


--
-- Name: member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member_oauth; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_oauth
(
    created_at     timestamp(6) with time zone NOT NULL,
    id             bigint                      NOT NULL,
    member_id      bigint                      NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL,
    oauth_provider character varying(20)       NOT NULL,
    provider_id    character varying(512)      NOT NULL,
    CONSTRAINT member_oauth_oauth_provider_check CHECK (((oauth_provider)::text = ANY ((ARRAY['GOOGLE':: character varying, 'APPLE':: character varying, 'KAKAO':: character varying])::text[])
) )
);


--
-- Name: member_oauth_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member_oauth ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_oauth_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_profile
(
    created_at timestamp(6) with time zone NOT NULL,
    id         bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    blog       character varying(255),
    github     character varying(255),
    instagram  character varying(255),
    linked_in  character varying(255),
    personal   character varying(255)
);


--
-- Name: member_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice
(
    should_send_notification boolean                     NOT NULL,
    author_member_id         bigint                      NOT NULL,
    created_at               timestamp(6) with time zone NOT NULL,
    id                       bigint                      NOT NULL,
    notified_at              timestamp(6) with time zone,
    updated_at               timestamp(6) with time zone NOT NULL,
    content                  character varying(3000)     NOT NULL,
    title                    character varying(255)      NOT NULL
);


--
-- Name: notice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notice_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice_image
(
    display_order integer                     NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    id            bigint                      NOT NULL,
    notice_id     bigint                      NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    image_id      character varying(255)      NOT NULL
);


--
-- Name: notice_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notice_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notice_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notice_link; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice_link
(
    display_order integer                     NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    id            bigint                      NOT NULL,
    notice_id     bigint                      NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    link          character varying(255)      NOT NULL
);


--
-- Name: notice_link_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notice_link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notice_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notice_read; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice_read
(
    challenger_id bigint                      NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    id            bigint                      NOT NULL,
    notice_id     bigint                      NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL
);


--
-- Name: notice_read_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notice_read ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notice_read_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notice_target; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice_target
(
    created_at             timestamp(6) with time zone NOT NULL,
    notice_id              bigint                      NOT NULL,
    target_chapter_id      bigint,
    target_gisu_id         bigint,
    target_school_id       bigint,
    updated_at             timestamp(6) with time zone NOT NULL,
    target_challenger_part smallint[]
);


--
-- Name: notice_vote; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notice_vote
(
    created_at timestamp(6) with time zone NOT NULL,
    id         bigint                      NOT NULL,
    notice_id  bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    vote_id    bigint                      NOT NULL
);


--
-- Name: notice_vote_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notice_vote ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notice_vote_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: original_workbook; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.original_workbook
(
    week_no       integer                     NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    curriculum_id bigint                      NOT NULL,
    end_date      timestamp(6) with time zone NOT NULL,
    id            bigint                      NOT NULL,
    released_at   timestamp(6) with time zone,
    start_date    timestamp(6) with time zone NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    description   character varying(255),
    mission_type  character varying(255)      NOT NULL,
    title         character varying(255)      NOT NULL,
    workbook_url  character varying(255),
    CONSTRAINT original_workbook_mission_type_check CHECK (((mission_type)::text = ANY ((ARRAY['LINK':: character varying, 'MEMO':: character varying, 'PLAIN':: character varying])::text[])
) )
);


--
-- Name: original_workbook_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.original_workbook ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.original_workbook_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post
(
    anonymous            boolean                     NOT NULL,
    max_participants     integer,
    author_challenger_id bigint                      NOT NULL,
    created_at           timestamp(6) with time zone NOT NULL,
    id                   bigint                      NOT NULL,
    meet_at              timestamp(6) without time zone,
    updated_at           timestamp(6) with time zone NOT NULL,
    category             character varying(255)      NOT NULL,
    content              text                        NOT NULL,
    location             character varying(255),
    open_chat_url        character varying(255),
    region               character varying(255)      NOT NULL,
    title                character varying(255)      NOT NULL,
    CONSTRAINT post_category_check CHECK (((category)::text = ANY ((ARRAY['LIGHTNING':: character varying, 'HABIT':: character varying, 'QUESTION':: character varying, 'INFORMATION':: character varying, 'FREE':: character varying])::text[])
) )
);


--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_like
(
    challenger_id bigint,
    post_id       bigint NOT NULL
);


--
-- Name: question; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.question
(
    is_required     boolean                     NOT NULL,
    order_no        integer                     NOT NULL,
    created_at      timestamp(6) with time zone NOT NULL,
    form_section_id bigint                      NOT NULL,
    id              bigint                      NOT NULL,
    updated_at      timestamp(6) with time zone NOT NULL,
    question_text   character varying(500)      NOT NULL,
    type            character varying(255)      NOT NULL,
    CONSTRAINT question_type_check CHECK (((type)::text = ANY ((ARRAY['SHORT_TEXT':: character varying, 'LONG_TEXT':: character varying, 'RADIO':: character varying, 'CHECKBOX':: character varying, 'DROPDOWN':: character varying, 'SCHEDULE':: character varying, 'PORTFOLIO':: character varying, 'PREFERRED_PART':: character varying])::text[])
) )
);


--
-- Name: question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: question_option; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.question_option
(
    is_other    boolean                     NOT NULL,
    order_no    integer                     NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL,
    id          bigint                      NOT NULL,
    question_id bigint,
    updated_at  timestamp(6) with time zone NOT NULL,
    content     character varying(255)      NOT NULL
);


--
-- Name: question_option_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.question_option ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruitment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruitment
(
    max_preferred_part_count integer,
    created_at               timestamp(6) with time zone NOT NULL,
    form_id                  bigint                      NOT NULL,
    gisu_id                  bigint,
    id                       bigint                      NOT NULL,
    parent_recruitment_id    bigint,
    published_at             timestamp(6) with time zone,
    root_recruitment_id      bigint,
    school_id                bigint,
    updated_at               timestamp(6) with time zone NOT NULL,
    notice_content           character varying(255),
    notice_title             character varying(255),
    status                   character varying(255),
    title                    character varying(255),
    interview_time_table     jsonb,
    CONSTRAINT recruitment_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT':: character varying, 'PUBLISHED':: character varying])::text[])
) )
);


--
-- Name: recruitment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recruitment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recruitment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruitment_part; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruitment_part
(
    created_at     timestamp(6) with time zone NOT NULL,
    id             bigint                      NOT NULL,
    recruitment_id bigint                      NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL,
    part           character varying(255)      NOT NULL,
    status         character varying(255)      NOT NULL,
    CONSTRAINT recruitment_part_part_check CHECK (((part)::text = ANY ((ARRAY['PLAN':: character varying, 'DESIGN':: character varying, 'WEB':: character varying, 'ANDROID':: character varying, 'IOS':: character varying, 'NODEJS':: character varying, 'SPRINGBOOT':: character varying])::text[])
) ),
    CONSTRAINT recruitment_part_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: recruitment_part_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recruitment_part ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recruitment_part_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recruitment_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recruitment_schedule
(
    created_at     timestamp(6) with time zone NOT NULL,
    ends_at        timestamp(6) with time zone,
    id             bigint                      NOT NULL,
    recruitment_id bigint                      NOT NULL,
    starts_at      timestamp(6) with time zone,
    updated_at     timestamp(6) with time zone NOT NULL,
    note           character varying(255),
    type           character varying(255)      NOT NULL,
    CONSTRAINT recruitment_schedule_type_check CHECK (((type)::text = ANY ((ARRAY['APPLY_WINDOW':: character varying, 'DOC_REVIEW_WINDOW':: character varying, 'DOC_RESULT_AT':: character varying, 'INTERVIEW_WINDOW':: character varying, 'FINAL_REVIEW_WINDOW':: character varying, 'FINAL_RESULT_AT':: character varying, 'OT_AT':: character varying, 'ACTIVITY_WINDOW':: character varying])::text[])
) )
);


--
-- Name: recruitment_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recruitment_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recruitment_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report
(
    created_at  timestamp(6) with time zone NOT NULL,
    id          bigint                      NOT NULL,
    reporter_id bigint                      NOT NULL,
    target_id   bigint                      NOT NULL,
    updated_at  timestamp(6) with time zone NOT NULL,
    reason      character varying(500),
    status      character varying(255)      NOT NULL,
    target_type character varying(255)      NOT NULL,
    CONSTRAINT report_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING':: character varying, 'APPROVED':: character varying, 'REJECTED':: character varying])::text[])
) ),
    CONSTRAINT report_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['POST'::character varying, 'COMMENT'::character varying])::text[])))
);


--
-- Name: report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule
(
    is_all_day           boolean                     NOT NULL,
    author_challenger_id bigint                      NOT NULL,
    created_at           timestamp(6) with time zone NOT NULL,
    ends_at              timestamp(6) with time zone NOT NULL,
    id                   bigint                      NOT NULL,
    starts_at            timestamp(6) with time zone NOT NULL,
    study_group_id       bigint,
    updated_at           timestamp(6) with time zone NOT NULL,
    description          text,
    location_name        character varying(255),
    name                 character varying(255)      NOT NULL,
    location public.geometry(Point,4326)
);


--
-- Name: schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule_tags
(
    schedule_id bigint NOT NULL,
    tag         character varying(255),
    CONSTRAINT schedule_tags_tag_check CHECK (((tag)::text = ANY ((ARRAY['LEADERSHIP':: character varying, 'STUDY':: character varying, 'DUES':: character varying, 'MEETING':: character varying, 'NETWORKING':: character varying, 'HACKATHON':: character varying, 'PROJECT':: character varying, 'PRESENTATION':: character varying, 'WORKSHOP':: character varying, 'RETROSPECTIVE':: character varying, 'AFTER_PARTY':: character varying, 'ORIENTATION':: character varying, 'GENERAL':: character varying])::text[])
) )
);


--
-- Name: school; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school
(
    created_at    timestamp(6) with time zone NOT NULL,
    id            bigint                      NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    logo_image_id character varying(255),
    name          character varying(255)      NOT NULL,
    remark        character varying(255)
);


--
-- Name: school_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_link; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_link
(
    created_at timestamp(6) with time zone NOT NULL,
    id         bigint                      NOT NULL,
    school_id  bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    title      character varying(255)      NOT NULL,
    type       character varying(255)      NOT NULL,
    url        character varying(255)      NOT NULL,
    CONSTRAINT school_link_type_check CHECK (((type)::text = ANY ((ARRAY['KAKAO':: character varying, 'YOUTUBE':: character varying, 'INSTAGRAM':: character varying])::text[])
) )
);


--
-- Name: school_link_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scrap; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scrap
(
    challenger_id bigint                      NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    id            bigint                      NOT NULL,
    post_id       bigint                      NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL
);


--
-- Name: scrap_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scrap ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scrap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: single_answer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.single_answer
(
    created_at       timestamp(6) with time zone NOT NULL,
    id               bigint                      NOT NULL,
    question_id      bigint                      NOT NULL,
    response_id      bigint                      NOT NULL,
    updated_at       timestamp(6) with time zone NOT NULL,
    answered_as_type character varying(255)      NOT NULL,
    value            jsonb                       NOT NULL,
    CONSTRAINT single_answer_answered_as_type_check CHECK (((answered_as_type)::text = ANY ((ARRAY['SHORT_TEXT':: character varying, 'LONG_TEXT':: character varying, 'RADIO':: character varying, 'CHECKBOX':: character varying, 'DROPDOWN':: character varying, 'SCHEDULE':: character varying, 'PORTFOLIO':: character varying, 'PREFERRED_PART':: character varying])::text[])
) )
);


--
-- Name: single_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.single_answer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.single_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: study_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.study_group
(
    created_at timestamp(6) with time zone NOT NULL,
    gisu_id    bigint,
    id         bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    name       character varying(255),
    part       character varying(255)      NOT NULL,
    CONSTRAINT study_group_part_check CHECK (((part)::text = ANY ((ARRAY['PLAN':: character varying, 'DESIGN':: character varying, 'WEB':: character varying, 'ANDROID':: character varying, 'IOS':: character varying, 'NODEJS':: character varying, 'SPRINGBOOT':: character varying])::text[])
) )
);


--
-- Name: study_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.study_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.study_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: study_group_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.study_group_member
(
    is_leader     boolean                     NOT NULL,
    challenger_id bigint                      NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    group_id      bigint,
    id            bigint                      NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL
);


--
-- Name: study_group_member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.study_group_member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.study_group_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: term; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.term
(
    active     boolean                     NOT NULL,
    required   boolean                     NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id         bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    link       character varying(255)      NOT NULL,
    type       character varying(255)      NOT NULL,
    CONSTRAINT term_type_check CHECK (((type)::text = ANY ((ARRAY['SERVICE':: character varying, 'PRIVACY':: character varying, 'MARKETING':: character varying, 'LOCATION':: character varying])::text[])
) )
);


--
-- Name: term_consent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.term_consent
(
    agreed_at  timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id         bigint                      NOT NULL,
    member_id  bigint                      NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    term_type  character varying(20)       NOT NULL,
    CONSTRAINT term_consent_term_type_check CHECK (((term_type)::text = ANY ((ARRAY['SERVICE':: character varying, 'PRIVACY':: character varying, 'MARKETING':: character varying, 'LOCATION':: character varying])::text[])
) )
);


--
-- Name: term_consent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.term_consent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.term_consent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: term_consent_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.term_consent_log
(
    created_at  timestamp(6) with time zone NOT NULL,
    id          bigint                      NOT NULL,
    member_id   bigint                      NOT NULL,
    occurred_at timestamp(6) with time zone NOT NULL,
    updated_at  timestamp(6) with time zone NOT NULL,
    status      character varying(20)       NOT NULL,
    term_type   character varying(20)       NOT NULL,
    CONSTRAINT term_consent_log_status_check CHECK (((status)::text = ANY ((ARRAY['AGREED':: character varying, 'WITHDRAWN':: character varying])::text[])
) ),
    CONSTRAINT term_consent_log_term_type_check CHECK (((term_type)::text = ANY ((ARRAY['SERVICE'::character varying, 'PRIVACY'::character varying, 'MARKETING'::character varying, 'LOCATION'::character varying])::text[])))
);


--
-- Name: term_consent_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.term_consent_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.term_consent_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: term_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.term ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.term_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trophy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trophy
(
    week          integer                     NOT NULL,
    challenger_id bigint                      NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    id            bigint                      NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL,
    content       text                        NOT NULL,
    title         character varying(255)      NOT NULL,
    url           character varying(255)      NOT NULL
);


--
-- Name: trophy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trophy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trophy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workbook_mission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workbook_mission
(
    created_at           timestamp(6) with time zone NOT NULL,
    id                   bigint                      NOT NULL,
    original_workbook_id bigint                      NOT NULL,
    updated_at           timestamp(6) with time zone NOT NULL,
    content              text,
    mission_type         character varying(255)      NOT NULL,
    title                character varying(255)      NOT NULL,
    CONSTRAINT workbook_mission_mission_type_check CHECK (((mission_type)::text = ANY ((ARRAY['LINK':: character varying, 'MEMO':: character varying, 'PLAIN':: character varying])::text[])
) )
);


--
-- Name: workbook_mission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workbook_mission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workbook_mission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_part_preference application_part_preference_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_part_preference
    ADD CONSTRAINT application_part_preference_pkey PRIMARY KEY (id);


--
-- Name: application application_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT application_pkey PRIMARY KEY (id);


--
-- Name: attendance_record attendance_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_record
    ADD CONSTRAINT attendance_record_pkey PRIMARY KEY (id);


--
-- Name: attendance_sheet attendance_sheet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_sheet
    ADD CONSTRAINT attendance_sheet_pkey PRIMARY KEY (id);


--
-- Name: central_organization central_organization_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.central_organization
    ADD CONSTRAINT central_organization_pkey PRIMARY KEY (id);


--
-- Name: challenger_mission challenger_mission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenger_mission
    ADD CONSTRAINT challenger_mission_pkey PRIMARY KEY (id);


--
-- Name: challenger challenger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenger
    ADD CONSTRAINT challenger_pkey PRIMARY KEY (id);


--
-- Name: challenger_point challenger_point_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenger_point
    ADD CONSTRAINT challenger_point_pkey PRIMARY KEY (id);


--
-- Name: challenger_record challenger_record_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenger_record
    ADD CONSTRAINT challenger_record_code_key UNIQUE (code);


--
-- Name: challenger_record challenger_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenger_record
    ADD CONSTRAINT challenger_record_pkey PRIMARY KEY (id);


--
-- Name: challenger_role challenger_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenger_role
    ADD CONSTRAINT challenger_role_pkey PRIMARY KEY (id);


--
-- Name: challenger_workbook challenger_workbook_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenger_workbook
    ADD CONSTRAINT challenger_workbook_pkey PRIMARY KEY (id);


--
-- Name: chapter chapter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter
    ADD CONSTRAINT chapter_pkey PRIMARY KEY (id);


--
-- Name: chapter_school chapter_school_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter_school
    ADD CONSTRAINT chapter_school_pkey PRIMARY KEY (id);


--
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- Name: curriculum curriculum_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.curriculum
    ADD CONSTRAINT curriculum_pkey PRIMARY KEY (id);


--
-- Name: email_verification email_verification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_verification
    ADD CONSTRAINT email_verification_pkey PRIMARY KEY (id);


--
-- Name: evaluation evaluation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluation
    ADD CONSTRAINT evaluation_pkey PRIMARY KEY (id);


--
-- Name: fcm_token fcm_token_member_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fcm_token
    ADD CONSTRAINT fcm_token_member_id_key UNIQUE (member_id);


--
-- Name: fcm_token fcm_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fcm_token
    ADD CONSTRAINT fcm_token_pkey PRIMARY KEY (id);


--
-- Name: file_metadata file_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_metadata
    ADD CONSTRAINT file_metadata_pkey PRIMARY KEY (id);


--
-- Name: file_metadata file_metadata_storage_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.file_metadata
    ADD CONSTRAINT file_metadata_storage_key_key UNIQUE (storage_key);


--
-- Name: form form_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form
    ADD CONSTRAINT form_pkey PRIMARY KEY (id);


--
-- Name: form_response form_response_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_response
    ADD CONSTRAINT form_response_pkey PRIMARY KEY (id);


--
-- Name: form_section form_section_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_section
    ADD CONSTRAINT form_section_pkey PRIMARY KEY (id);


--
-- Name: gisu gisu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gisu
    ADD CONSTRAINT gisu_pkey PRIMARY KEY (id);


--
-- Name: interview_assignment interview_assignment_application_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_assignment
    ADD CONSTRAINT interview_assignment_application_id_key UNIQUE (application_id);


--
-- Name: interview_assignment interview_assignment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_assignment
    ADD CONSTRAINT interview_assignment_pkey PRIMARY KEY (id);


--
-- Name: interview_live_question interview_live_question_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_live_question
    ADD CONSTRAINT interview_live_question_pkey PRIMARY KEY (id);


--
-- Name: interview_question_sheet interview_question_sheet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_question_sheet
    ADD CONSTRAINT interview_question_sheet_pkey PRIMARY KEY (id);


--
-- Name: interview_slot interview_slot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_slot
    ADD CONSTRAINT interview_slot_pkey PRIMARY KEY (id);


--
-- Name: member_oauth member_oauth_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_oauth
    ADD CONSTRAINT member_oauth_pkey PRIMARY KEY (id);


--
-- Name: member member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);


--
-- Name: member member_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_profile_id_key UNIQUE (profile_id);


--
-- Name: member_profile member_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_profile
    ADD CONSTRAINT member_profile_pkey PRIMARY KEY (id);


--
-- Name: notice_image notice_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_image
    ADD CONSTRAINT notice_image_pkey PRIMARY KEY (id);


--
-- Name: notice_link notice_link_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_link
    ADD CONSTRAINT notice_link_pkey PRIMARY KEY (id);


--
-- Name: notice notice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice
    ADD CONSTRAINT notice_pkey PRIMARY KEY (id);


--
-- Name: notice_read notice_read_notice_id_challenger_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_read
    ADD CONSTRAINT notice_read_notice_id_challenger_id_key UNIQUE (notice_id, challenger_id);


--
-- Name: notice_read notice_read_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_read
    ADD CONSTRAINT notice_read_pkey PRIMARY KEY (id);


--
-- Name: notice_target notice_target_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_target
    ADD CONSTRAINT notice_target_pkey PRIMARY KEY (notice_id);


--
-- Name: notice_vote notice_vote_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_vote
    ADD CONSTRAINT notice_vote_pkey PRIMARY KEY (id);


--
-- Name: original_workbook original_workbook_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.original_workbook
    ADD CONSTRAINT original_workbook_pkey PRIMARY KEY (id);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- Name: question_option question_option_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question_option
    ADD CONSTRAINT question_option_pkey PRIMARY KEY (id);


--
-- Name: question question_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT question_pkey PRIMARY KEY (id);


--
-- Name: recruitment_part recruitment_part_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment_part
    ADD CONSTRAINT recruitment_part_pkey PRIMARY KEY (id);


--
-- Name: recruitment recruitment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment
    ADD CONSTRAINT recruitment_pkey PRIMARY KEY (id);


--
-- Name: recruitment_schedule recruitment_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recruitment_schedule
    ADD CONSTRAINT recruitment_schedule_pkey PRIMARY KEY (id);


--
-- Name: report report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT report_pkey PRIMARY KEY (id);


--
-- Name: schedule schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule
    ADD CONSTRAINT schedule_pkey PRIMARY KEY (id);


--
-- Name: school_link school_link_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_link
    ADD CONSTRAINT school_link_pkey PRIMARY KEY (id);


--
-- Name: school school_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school
    ADD CONSTRAINT school_pkey PRIMARY KEY (id);


--
-- Name: scrap scrap_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrap
    ADD CONSTRAINT scrap_pkey PRIMARY KEY (id);


--
-- Name: scrap scrap_post_id_challenger_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrap
    ADD CONSTRAINT scrap_post_id_challenger_id_key UNIQUE (post_id, challenger_id);


--
-- Name: single_answer single_answer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.single_answer
    ADD CONSTRAINT single_answer_pkey PRIMARY KEY (id);


--
-- Name: study_group_member study_group_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.study_group_member
    ADD CONSTRAINT study_group_member_pkey PRIMARY KEY (id);


--
-- Name: study_group study_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.study_group
    ADD CONSTRAINT study_group_pkey PRIMARY KEY (id);


--
-- Name: term_consent_log term_consent_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.term_consent_log
    ADD CONSTRAINT term_consent_log_pkey PRIMARY KEY (id);


--
-- Name: term_consent term_consent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.term_consent
    ADD CONSTRAINT term_consent_pkey PRIMARY KEY (id);


--
-- Name: term term_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.term
    ADD CONSTRAINT term_pkey PRIMARY KEY (id);


--
-- Name: trophy trophy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trophy
    ADD CONSTRAINT trophy_pkey PRIMARY KEY (id);


--
-- Name: chapter uk_chapter_gisu_id_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter
    ADD CONSTRAINT uk_chapter_gisu_id_name UNIQUE (gisu_id, name);


--
-- Name: member_oauth uk_member_oauth_provider_provider_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_oauth
    ADD CONSTRAINT uk_member_oauth_provider_provider_id UNIQUE (oauth_provider, provider_id);


--
-- Name: workbook_mission workbook_mission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workbook_mission
    ADD CONSTRAINT workbook_mission_pkey PRIMARY KEY (id);


--
-- Name: notice_image fk13h2d99jqpw7xnaj5w1crvv8m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_image
    ADD CONSTRAINT fk_notice_image_notice_id FOREIGN KEY (notice_id) REFERENCES public.notice(id);


--
-- Name: interview_live_question fk21dce1i2wlk8ndk1jbiyutoc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_live_question
    ADD CONSTRAINT fk_interview_live_q_appl_id FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: central_organization fk2abyl3i2l2esjexkdlqg1lfyu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.central_organization
    ADD CONSTRAINT fk_central_org_gisu_id FOREIGN KEY (gisu_id) REFERENCES public.gisu(id);


--
-- Name: question fk30lyi8qkalpwcjew60oahaa99; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question
    ADD CONSTRAINT fk_question_form_sect_id FOREIGN KEY (form_section_id) REFERENCES public.form_section(id);


--
-- Name: application_part_preference fk3hamnhjhnk6c4357rtd4snl3w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_part_preference
    ADD CONSTRAINT fk_appl_part_pref_recruit_part_id FOREIGN KEY (recruitment_part_id) REFERENCES public.recruitment_part(id);


--
-- Name: challenger_point fk3j6c463flsyfd1mt8hip0xuvg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenger_point
    ADD CONSTRAINT fk_challenger_point_chall_id FOREIGN KEY (challenger_id) REFERENCES public.challenger(id);


--
-- Name: challenger_mission fk48bd420ph229fccdgtsdaoxmj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenger_mission
    ADD CONSTRAINT fk_challenger_mission_workbook_id FOREIGN KEY (challenger_workbook_id) REFERENCES public.challenger_workbook(id);


--
-- Name: form_response fk4sed41etq9jpqi0pskh7yukrv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_response
    ADD CONSTRAINT fk_form_response_form_id FOREIGN KEY (form_id) REFERENCES public.form(id);


--
-- Name: school_link fk55yka7wfnmweyu36oypae5gve; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_link
    ADD CONSTRAINT fk_school_link_school_id FOREIGN KEY (school_id) REFERENCES public.school(id);


--
-- Name: interview_slot fk5d4rto78f6rcvxf5ptgi255ir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_slot
    ADD CONSTRAINT fk_interview_slot_recr_id FOREIGN KEY (recruitment_id) REFERENCES public.recruitment(id);


--
-- Name: evaluation fk8kmneeb146rbmsvm1jkhoy1s9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.evaluation
    ADD CONSTRAINT fk_evaluation_appl_id FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: original_workbook fk9mrmn4qk5lpxnhordx9jx0bdd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.original_workbook
    ADD CONSTRAINT fk_org_workbook_curr_id FOREIGN KEY (curriculum_id) REFERENCES public.curriculum(id);


--
-- Name: chapter fkbhht5p1907cjerhqptxmkd5j8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter
    ADD CONSTRAINT fk_chapter_gisu_id FOREIGN KEY (gisu_id) REFERENCES public.gisu(id);


--
-- Name: interview_assignment fkbiuwjuthpeeytmd7tqp8egi3v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_assignment
    ADD CONSTRAINT fk_interview_assign_appl_id FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: study_group fkf0d4m9b1yjhn4tgggk4ceyjmo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.study_group
    ADD CONSTRAINT fk_study_group_gisu_id FOREIGN KEY (gisu_id) REFERENCES public.gisu(id);


--
-- Name: fcm_token fkf1rbjf8lle4r2in6ovkcgl0w8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fcm_token
    ADD CONSTRAINT fk_fcm_token_member_id FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- Name: notice_read fkfadagonkeggnjqyuy10d4qego; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_read
    ADD CONSTRAINT fk_notice_read_notice_id FOREIGN KEY (notice_id) REFERENCES public.notice(id);


--
-- Name: notice_link fkffr7h4dyleo02gf9mtda2qg0p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_link
    ADD CONSTRAINT fk_notice_link_notice_id FOREIGN KEY (notice_id) REFERENCES public.notice(id);


--
-- Name: interview_assignment fkghgtyrf4074eti8dtlcnv6hra; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_assignment
    ADD CONSTRAINT fk_interview_assign_slot_id FOREIGN KEY (slot_id) REFERENCES public.interview_slot(id);


--
-- Name: interview_question_sheet fkhehe0a4w8tjmvasot5wj7kwh4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_question_sheet
    ADD CONSTRAINT fk_interview_ques_sheet_recr_id FOREIGN KEY (recruitment_id) REFERENCES public.recruitment(id);


--
-- Name: member fki5sgf3h2nfnd3f0rj53phsoaw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT fk_member_profile_id FOREIGN KEY (profile_id) REFERENCES public.member_profile(id);


--
-- Name: schedule_tags fkj535dukyciblkrvyqpk0nnp4y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule_tags
    ADD CONSTRAINT fk_schedule_tags_schedule_id FOREIGN KEY (schedule_id) REFERENCES public.schedule(id);


--
-- Name: post_like fkj7iy0k7n3d0vkh8o7ibjna884; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_like
    ADD CONSTRAINT fk_post_like_post_id FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: single_answer fkki99x99hyoalet42fu2ro4lic; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.single_answer
    ADD CONSTRAINT fk_single_answer_response_id FOREIGN KEY (response_id) REFERENCES public.form_response(id);


--
-- Name: chapter_school fkkjdylii7vlq5n2a5tapt2p9an; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter_school
    ADD CONSTRAINT fk_chapter_school_chapter_id FOREIGN KEY (chapter_id) REFERENCES public.chapter(id);


--
-- Name: question_option fkmmdv54rmm5hkgxbn1008ix87n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question_option
    ADD CONSTRAINT fk_question_option_question_id FOREIGN KEY (question_id) REFERENCES public.question(id);


--
-- Name: chapter_school fkmrnimigsrr31m9dxs8tjqip4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter_school
    ADD CONSTRAINT fk_chapter_school_school_id FOREIGN KEY (school_id) REFERENCES public.school(id);


--
-- Name: application_part_preference fkmrpw0lo117yicx1wvrdto4c0y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_part_preference
    ADD CONSTRAINT fk_appl_part_pref_appl_id FOREIGN KEY (application_id) REFERENCES public.application(id);


--
-- Name: interview_assignment fkn9iegbrvvq8q6dcwr0l0ljpj8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_assignment
    ADD CONSTRAINT fk_interview_assign_recr_id FOREIGN KEY (recruitment_id) REFERENCES public.recruitment(id);


--
-- Name: study_group_member fkok74qotmd7xqy9wvews3xv8iu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.study_group_member
    ADD CONSTRAINT fk_study_group_member_member_id FOREIGN KEY (group_id) REFERENCES public.study_group(id);


--
-- Name: notice_vote fkp6as401tgeia8hn1uo2de199f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notice_vote
    ADD CONSTRAINT fk_notice_vote_notice_id FOREIGN KEY (notice_id) REFERENCES public.notice(id);


--
-- Name: application fkp6pay5d5qymslgxs3d7ukepib; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application
    ADD CONSTRAINT fk_appl_recr_id FOREIGN KEY (recruitment_id) REFERENCES public.recruitment(id);


--
-- Name: single_answer fkpebjm0gybir74o50037lhvmsu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.single_answer
    ADD CONSTRAINT fk_single_answer_question_id FOREIGN KEY (question_id) REFERENCES public.question(id);


--
-- Name: form_section fkpvynqwi2t1wrw3wv1imaidi8s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.form_section
    ADD CONSTRAINT fk_form_section_form_id FOREIGN KEY (form_id) REFERENCES public.form(id);


--
-- Name: comment_like fkqlv8phl1ibeh0efv4dbn3720p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comment_like
    ADD CONSTRAINT fk_comment_like_comment_id FOREIGN KEY (comment_id) REFERENCES public.comment(id);
