CREATE TABLE inquiry
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE                NOT NULL,
    title               VARCHAR(255)                            NOT NULL,
    content             TEXT                                    NOT NULL,
    category            VARCHAR(30)                             NOT NULL,
    target              VARCHAR(20)                             NOT NULL,
    status              VARCHAR(20)                             NOT NULL DEFAULT 'RECEIVED',
    chat_room_id        BIGINT                                  NOT NULL,
    target_school_id    BIGINT,
    target_chapter_id   BIGINT,
    target_gisu_id      BIGINT,
    author_member_id    BIGINT                                  NOT NULL,
    assigned_member_ids BIGINT[]                                NOT NULL DEFAULT '{}',
    file_metadata_ids   TEXT[]                                  NOT NULL DEFAULT '{}',
    is_read             BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_inquiry PRIMARY KEY (id)
);

-- 문의 ↔ 채팅방은 1:1. 조회 경로(findByChatRoomId → Optional)와 정합성을 UNIQUE 로 보장한다.
-- 채팅방(chat_room)은 별도 바운디드 컨텍스트라 FK 는 두지 않고 애플리케이션 레벨에서 무결성을 보장한다.
CREATE UNIQUE INDEX uq_inquiry_chat_room_id ON inquiry (chat_room_id);


