CREATE TABLE answer
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    form_response_id BIGINT                                  NOT NULL,
    question_id      BIGINT                                  NOT NULL,
    text_value       TEXT,
    answered_as_type VARCHAR(255)                            NOT NULL,
    file_ids         BIGINT[],
    times            TIMESTAMPTZ[],
    CONSTRAINT pk_answer PRIMARY KEY (id)
);

CREATE TABLE answer_choice
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    answer_id           BIGINT                                  NOT NULL,
    answered_as_content VARCHAR(500)                            NOT NULL,
    question_option_id  BIGINT,
    CONSTRAINT pk_answer_choice PRIMARY KEY (id)
);

ALTER TABLE answer_choice
    ADD CONSTRAINT FK_ANSWER_CHOICE_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answer (id);

ALTER TABLE answer_choice
    ADD CONSTRAINT FK_ANSWER_CHOICE_ON_QUESTION_OPTION FOREIGN KEY (question_option_id) REFERENCES question_option (id) ON DELETE SET NULL;

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_FORM_RESPONSE FOREIGN KEY (form_response_id) REFERENCES form_response (id);

ALTER TABLE answer
    ADD CONSTRAINT FK_ANSWER_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

ALTER TABLE question_option
    ALTER COLUMN content TYPE VARCHAR(500);
