--- study_group_schedule 테이블 생성

CREATE TABLE public.study_group_schedule
(
    id             bigint                      NOT NULL,
    study_group_id bigint                      NOT NULL,
    schedule_id    bigint                      NOT NULL,
    created_at     timestamp(6) with time zone NOT NULL,
    updated_at     timestamp(6) with time zone NOT NULL
);

ALTER TABLE public.study_group_schedule
    ALTER
        COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.study_group_schedule_id_seq
        START WITH 1 INCREMENT BY 1
        NO MINVALUE NO MAXVALUE CACHE 1
        );

ALTER TABLE ONLY public.study_group_schedule
    ADD CONSTRAINT study_group_schedule_pkey PRIMARY KEY (id);
