CREATE TABLE chat_room
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_chat_room PRIMARY KEY (id)
);

CREATE TABLE chat_member
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    room_id    BIGINT                                  NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_chat_member PRIMARY KEY (id),
    CONSTRAINT uq_chat_member_room_member UNIQUE (room_id, member_id)
);

ALTER TABLE chat_member
    ADD CONSTRAINT fk_chat_member_room FOREIGN KEY (room_id) REFERENCES chat_room (id) ON DELETE CASCADE;
